### ISSUE TITLE
Need old version of instructions for Module 3

### ISSUE THREAD

**Issue by aaronjthorpe** [MicrosoftLearning/DP-203-Data-Engineer#1]
# Module: 03
#### Step: All

I am teaching the old version of DP-203 this week (26 June)  I need the scenario for the Module 3 ("whiteboard") lab.  It is not included in the Skillpipe book.

**Comment by ctesta-oneillmsft** [comment]
Here you go

https://github.com/MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure
