### ISSUE TITLE
Task 5: Test permissions step 7 of LAB_02_queries_using_serverless_sql_pools.md contains wrong instruction

### ISSUE THREAD

**Issue by jorikwortell** [MicrosoftLearning/DP-203-Data-Engineer#108]
Code in step 7 "Enter the following code, replacing SUFFIX with the unique suffix for your data lake resource (you can copy this from cell 1 above):" 
refers to the 2019 file (and a space in front, which makes pasting-and-running harder)

df.write.parquet('abfss://wwi-02@asadatalakeSUFFIX.dfs.core.windows.net/sale-small/Year=2019/Quarter=Q4/Month=12/Day=20191231/sale-small-20191231-snappy-test.parquet')

This should be the 2016 file:

 df.write.parquet('abfss://wwi-02@asadatalakeSUFFIX.dfs.core.windows.net/sale-small/Year=2016/Quarter=Q4/Month=12/Day=20161231/sale-small-20161231-snappy-test.parquet')

**Comment by TheJamesHerring** [comment]
Updated content to allow for showing error.  Thanks for catch.
