### ISSUE TITLE
Lab 4 error in folder name

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-203-Data-Engineer#11]
# Module: 04
#### Step: 4

Description of issue
Lab 4, Exercise 0, Task 2, Step 4 - missing hyphen:  change dp203 to dp-203
Repro steps:

cd C:\dp203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\

change to:
cd C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\

**Comment by ctesta-oneillmsft** [comment]
resolved
