### ISSUE TITLE
Lab 6: Pipeline publish fail w/error. 

### ISSUE THREAD

**Issue by Johnny-5-Alive77** [MicrosoftLearning/DP-203-Data-Engineer#111]
# Lab: 6
#### Step: 9

Description of issue
Unable to publish pipeline changes to the dataflow per step 9. Validation error returned.
![image](https://user-images.githubusercontent.com/73357132/156624547-c6aa0a25-2b86-4df7-a2b5-a81483c2117c.png)

**Comment by TheJamesHerring** [comment]
unable to repeat this error, please let me know if it persists.  It's possible a step was missed in the directions.

**Comment by molenaar** [comment]
Is the SQL dedicated pool started?

Has the setup parts 03 been running correctly and is Cosmos filled with all the necessary data?
