### ISSUE TITLE
Lab 06 Exercise 2 Verify the script

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/DP-203-Data-Engineer#112]
# Module: 06
#### Step: 11

Description of issue
erify that the script looks like this and then Cancel to return the graphical UI (if not, modify the script):

source(output(
        visitorId as string,
        topProductPurchases as (productId as string, itemsPurchasedLast12Months as string)[]
    ),
    allowSchemaDrift: true,
    validateSchema: false,
    ignoreNoFilesFound: false,
    documentForm: 'arrayOfDocuments',

Real output:
source(output(
		visitorId as **integer**,
		topProductPurchases as (productId as **integer**, itemsPurchasedLast12Months as **integer**)[]
	),
	allowSchemaDrift: true,
	validateSchema: false,
	ignoreNoFilesFound: false,
	documentForm: 'arrayOfDocuments',

Repro steps:

1.
1.
1.

**Comment by TheJamesHerring** [comment]
The comments concerning this lab ask the student to verift that the script looks like:

source(output(
        visitorId as string,
        topProductPurchases as (productId as string, itemsPurchasedLast12Months as string)[]
    ),
    allowSchemaDrift: true,
    validateSchema: false,
    ignoreNoFilesFound: false,
    documentForm: 'arrayOfDocuments',
    wildcardPaths:['online-user-profiles-02/*.json']) ~> EcommerceUserProfiles
EcommerceUserProfiles derive(visitorId = toInteger(visitorId)) ~> userId
userId foldDown(unroll(topProductPurchases),
    mapColumn(
        visitorId,
        productId = topProductPurchases.productId,
        itemsPurchasedLast12Months = topProductPurchases.itemsPurchasedLast12Months
    ),
    skipDuplicateMapInputs: false,
    skipDuplicateMapOutputs: false) ~> UserTopProducts

And if not, to modify the script.  It looks as though, yours needs modified per the directions.  Let me know if this doesn't work for you.
