### ISSUE TITLE
Setup script for part02 is relying on variables from part01 whuch causes problems if needing to rerun part01

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203-Data-Engineer#114]
# Module: 01
#### Step: 00

Description of issue
When a deployment occurs with potential failures of certain parts, the variables from part01 via the code are referenced in part02. This includes the unique suffix value amongst other items. I noticed that if the code needs to be rerun to handle any failed deployment components (CosmosDB, etc..) the variables are not updated in the reference to part02. Not sure why those values are pulled from previous script when these values can be pulled using Az cmdlets.
Repro steps:

1.
1.
1.

**Comment by TheJamesHerring** [comment]
Stay tuned, things will be changing as we're working on some transitioning on the team and look to re-vamp much of labs.
