### ISSUE TITLE
Please remove SouthCentral Region as deployment option

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203-Data-Engineer#115]
# Module: 00
#### Step: 00

Description of issue
Cosmos DB has reached its limit in this region and this particular deployment fails every time this region is selected. Can we remove this region as a deployment option?
Repro steps:

1.
1.
1.

**Comment by molenaar** [comment]
Agree. South Central us is causing lots of error. Also with provisioning database clusters (different issue)

And remove the unnecessary database resources check in the script. Too much time.

Better provide a list of locations so students can pick their location nearby. Or the trainer can prefer a location that definitely works.

**Comment by TheJamesHerring** [comment]
Removed SouthCentralUS - should not allow in next git clone.
