### ISSUE TITLE
Module 2 - Incorrect year reference to 2016 instead of 2019

### ISSUE THREAD

**Issue by dphugo** [MicrosoftLearning/DP-203-Data-Engineer#118]
# Module: 02
#### Step: 07

Description of issue:

Task 4 and 5 refers to 2019 as the year directory for the demo, but the screenshots and Task5-Step7 refers to 2016.

[Link to issue](https://github.com/MicrosoftLearning/DP-203-Data-Engineer/blob/master/Instructions/Labs/LAB_02_queries_using_serverless_sql_pools.md#task-5-test-permissions)

**Comment by TheJamesHerring** [comment]
@dphugo This should be correct now, PDETS was asked to wait till the end of the week to change; however, if it persists please let me know.

**Comment by dphugo** [comment]
The issue persists. 
It should be 2019 not 2016.

It was changed here: `https://github.com/MicrosoftLearning/DP-203-Data-Engineer/commit/f5e44c7ea741b0d2de0dac0987d304d28efb82f8`


![image](https://user-images.githubusercontent.com/22542589/160634049-034eba98-061e-4939-af4d-050d677ccb07.png)
