### ISSUE TITLE
Setup in 3 parts

### ISSUE THREAD

**Issue by Derekp20** [MicrosoftLearning/DP-203-Data-Engineer#119]
# Module: 00
#### Step: 00

The setup script is now in 3 parts. If the VM is reset for any reason, you need to redownload the setup files from Github and edit the dp-203-setup-part02.ps1 and dp-203-setup-part03.ps1 files to include the parts that are automatically added when the setup is run. I was teaching this revised version for the first time this week, and had several whose VM was not saved, or was reset by the lab provider. Took me a while to workout why the 02 and 03 parts would not work. You can see what needs to be added from the end of part01 and part02. all the values can be copied from the Azure portal.

Maybe some Powershell wizzkid could write a script that will fix this. I had to edit this info for 4 students. I might get students to run this scripts in quick succession on the first day to avoid this problem.

**Comment by douwevandenberg** [comment]
In spite of this course being available for quite some time now, I experienced issues with these three (four) steps at an ALH as well, when each lab was executed on a fresh environment. Instructions were missing, repo hadn't been cloned and of course the files of setup 2, 3 hadn't been edited so had no idea where to go.

**Comment by douwevandenberg** [comment]
The problem isn't a reset. It's a completely NEW vm at some lab hosters, fresh without even the github repo yet. So you could clone the repo again (which takes a bit too long to repeat every time) but then obviously the values haven't been adjusted.

**Comment by Derekp20** [comment]
Yes this the issue. The VMs provided by lab hosters have a habit of being reset unexpectly. As a result all the info that was downloaded from the repo is lost, including the modifications to the parts 2 and 3 of the script. The solution seems to be to run the 3 parts on the first day. I have had VMs reset over night on several occasions. The SQLSetup part prompts for the resource group name, maybe the other scripts can be modified to do this.
