### ISSUE TITLE
vCPU Limits Exceeded For Azure Pass Solution

### ISSUE THREAD

**Issue by berkenbrack** [MicrosoftLearning/DP-203-Data-Engineer#12]
## Lab/Demo: 01

Description of issue:  The instructions for the Databricks cluster setup provisions the service with more vCPUs than the provided Azure Passes allow. 

Potential solution:  Set the cluster to have a min workers =1 and max workers = 2.

**Comment by ctesta-oneillmsft** [comment]
resolved
