### ISSUE TITLE
VM for databricks cluster not available in <region>

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/DP-203-Data-Engineer#120]
# Module: 01
## Lab/Demo: 01

Description of issue
See issue 110 (https://github.com/MicrosoftLearning/DP-203-Data-Engineer/issues/110). Something similar happened to my class, now with the Central US region. I then tried another region (West EU), same issue. The VMs are not available (for Azure Pass subscriptions, I think?). East Australia did work, so we modified setup 1 to use that region. Which, I know, is not what the intention of the random regions is.

Repro steps:
Get unlucky during setup 1 in lab 0.

**Comment by erikvani** [comment]
Had the same issue days ago. One student had the error for different regions.
