### ISSUE TITLE
Lab3: Datetime manipulation notebook contains strikethrough text

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/DP-203-Data-Engineer#123]
# Module: 3
#### Task: 2

Description of issue
Cell 8 of the notebook (1.DateTime-Manipulation) contains some strikethrough text that seems rather out of place. I guess an earlier edit?

Repro steps:
Just import the notebooks as the lab steps tell you.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by TheJamesHerring** [comment]
Removed leftover notes
