### ISSUE TITLE
setup_sql.ps1, Error to create objects in SQLPOOL

### ISSUE THREAD

**Issue by Israelsmmx** [MicrosoftLearning/DP-203-Data-Engineer#125]
# Module: Data Engineering on Microsoft Azure DP203-a
#### Step: 03 Enter the following command to run a PowerShell script that creates objects in the SQL pool: .\setup-sql.ps1

Description of issue

The PS script execution request account & Resource group
I used @outlook account for that no issues is a new account,is requesed the Resource group such as data-engineering-synapse-xxxxxxx) , during the execution appears some issues with the script that is not able to locate some resources

![image](https://user-images.githubusercontent.com/84999244/160868692-2354d448-841c-4287-86af-a9520ccaa7fe.png)

Invoke-SqlCmd : Could not load file or assembly 'Microsoft.SqlServer.BatchParser, Version=15.100.0.0,
Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The system cannot find the file
specified.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\solliance-synapse-automat
ion\solliance-synapse-automation.psm1:1114 char:13
+             Invoke-SqlCmd -Query $sqlQuery -ServerInstance $sqlEndpoi ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Sqlcmd], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.SqlServer.Management.PowerShell.GetSc
   riptCommand

I removed the resources and SQLPool, 
Restart the VM, 
Try in a  different PCs with no issues on connections, 
Ethernet conectivity 
Download the last version of PS files from the Repo

and fails in each execution following the instructions.

**Comment by GraemeMalcolm** [comment]
@TheJamesHerring 
If this is non-repro, please close it.
