### ISSUE TITLE
Lab 08, Ex 2 Task 3 Step2: UI update requires setting not in instructions

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203-Data-Engineer#130]
# Module: 08
#### Step: 02

Description of issue
There has been a UI update that requires that you select system or user managed identity and the instructions dont refect that update 
Repro steps:

1.
1.
![webinputupdate](https://user-images.githubusercontent.com/46732841/162221442-3b6f5b81-0394-4380-aeff-89a7b23b907d.png)

**Comment by TheJamesHerring** [comment]
Lab 8, Task 2, Step 8.4 Updated
