### ISSUE TITLE
Lab 8 Ex1, Task 1, Step 2

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203-Data-Engineer#131]
# Module: 08
#### Step: 02

Description of issue
UI has updated and image is not representative of what students see - tab is called Azure Active Directory
![Screenshot 2022-04-07 092606](https://user-images.githubusercontent.com/46732841/162222327-f735b4d1-a354-4681-8f70-150eefaaab9c.png)

Repro steps:

1.
1.
1.

**Comment by TheJamesHerring** [comment]
Updated directions to reflect and image
