### ISSUE TITLE
GRS List and Create Container Operations eating more than $80 from sponsorship pass.

### ISSUE THREAD

**Issue by azurearchitect786** [MicrosoftLearning/DP-203-Data-Engineer#132]
1. In DP-203 Labs, we observed an anomaly that even without any misconfigurations, one of our participant lost more than $80 on storage account operations.

Kindly suggest reason that why storage has spent so much instead of costly resources like synapse pools and databricks clusters.

Thanks

**Comment by molenaar** [comment]
Yes, I remember one of my students had that too. Ended up with spending more than $180 and a disabled azure pass at day 3. New azure pass and started all over again.....

**Comment by TheJamesHerring** [comment]
The GRS option should have been turned off, please open a ticket through Azure Support, there is nothing that I can do on this end for billing issues (even for Azure Passes).
