### ISSUE TITLE
Lab9 Task2

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/DP-203-Data-Engineer#134]
# Module: 09
#### Step: 00

Description of issue

"Tailwind Traders has an Azure Cosmos DB container named OnlineUserProfile01. Since we enabled the Azure Synapse Link feature after the container was already created, we cannot enable the analytical store on the container. We will create a new container that has the same partition key and enable the analytical store.

After creating the container, we will create a new Synapse Pipeline to copy data from the OnlineUserProfile01 container to the new one."

[Since March 30 2022, a new update has been implemented](https://devblogs.microsoft.com/cosmosdb/azure-synapse-link-existing-containers-and-power-bi-integration/?msclkid=afd1b0f4d12f11ecaa50171c20031968) which means Task 2 is no longer necessary. 

Repro steps:

1. Can be removed 
2. 1. New steps can be Select containers to enable Azure Synapse Link for your containers entering the Synapse Link page

**Comment by TheJamesHerring** [comment]
Will take a look at the lab. Thanks.

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review confirms this issue.

**Comment by TheJamesHerring** [comment]
Removed Task 2 which contained pre-3/30/2022 steps and re-numbered Task 3 to Task 2
