### ISSUE TITLE
Lab 2, Exercise 2, Task 5, Step 19 change 2019 to 2016

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-203-Data-Engineer#136]
# Module: 02
## Lab/Demo: 02  
###Exercise 2
#### Step: 19

Description of issue
In Synapse Studio, in the Data hub, on the Linked tab select the Azure Data Lake Storage Gen2/asaworkspacexxxxxxx/wwi02 container; and browse to the sale-small/Year=2019/Quarter=Q4/Month=12/Day=20191231 folder to verify that a new file has been added to this folder.

should be:
In Synapse Studio, in the Data hub, on the Linked tab select the Azure Data Lake Storage Gen2/asaworkspacexxxxxxx/wwi02 container; and browse to the sale-small/Year=2016/Quarter=Q4/Month=12/Day=20161231 folder to verify that a new file has been added to this folder.
Repro steps:
Image is correct. Change instructions text to reflect image; change 2019 to 2016

**Comment by MOC-Labs-Review** [comment]
MOC Labs Review did not experience this issue.

**Comment by VitalyMCT** [comment]
@TheJamesHerring 

My fellow MCT colleague @TammySmithMCT is correct, this is an issue. @MOC-Labs-Review erred in making the comment.

My students just ran into this again today:

![image](https://user-images.githubusercontent.com/1765732/170353819-fd75033f-49e3-4351-8ed7-e1d81c461162.png)
