### ISSUE TITLE
Lab 1 - Task Numbering and Markdown

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#137]
Task numbering jumps from 3 to 2 towards the end of Exercise 1. Also, the "cluster shutdown" reminder should probably have corresponding Markdown or its own task for consistency with the rest of the instructions. See screenshot below for both issue.

![image](https://user-images.githubusercontent.com/1765732/169672359-2acbe38a-fd42-4a94-959a-80eafe6c8575.png)

**Comment by TheJamesHerring** [comment]
This was updated some time ago.  When did you do your latest git clone?  I'll check skillpipe vendor, they're performing a review as well. but when a new lab is started, it should pull current labs from Git.  TY, JH

**Comment by VitalyMCT** [comment]
@TheJamesHerring It's not git clone, it's in the live repo: https://github.com/MicrosoftLearning/DP-203-Data-Engineer/blob/master/Instructions/Labs/LAB_01_compute_and_storage_options.md
