### ISSUE TITLE
Provisioning error in setup script

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#139]
See screenshot below.

![image](https://user-images.githubusercontent.com/1765732/169726740-1509ffeb-7fd6-41a2-b089-a69f321e0d2d.png)

**Comment by VitalyMCT** [comment]
The attendee also noticed an error when trying to instantiate the cluster:

MessageCluster terminated.Reason:Cloud provider launch failureA cloud provider error was encountered while launching worker nodes. See the Databricks guide for more information.Azure error code: PublicIPCountLimitReachedAzure error message: Cannot create more than 10 public IP addresses for this subscription in this region. (Azure request Id: 3075bafa-2aa6-4fe9-9067-a4dfbec0d6e4)
{
  "reason": {
    "code": "CLOUD_PROVIDER_LAUNCH_FAILURE",
    "type": "CLOUD_FAILURE",
    "parameters": {
      "azure_error_code": "PublicIPCountLimitReached",
      "azure_error_message": "Cannot create more than 10 public IP addresses for this subscription in this region. (Azure request Id: 3075bafa-2aa6-4fe9-9067-a4dfbec0d6e4)",
      "databricks_error_message": "Error code: PublicIPCountLimitReached, error message: Cannot create more than 10 public IP addresses for this subscription in this region. (Azure request Id: 3075bafa-2aa6-4fe9-9067-a4dfbec0d6e4)"
    }
  }
}

**Comment by TheJamesHerring** [comment]
I've removed Eastus2 from the list of supported regions.  Can you tell me if this was a student working from a location in the continental United States?

**Comment by VitalyMCT** [comment]
Yes, most if not all of the students who've experienced the error this week were from the continental US.

I think the challenge is that the script is currently only checking provisioning/resource constraints for the Azure SQL database. From time to time other services can also fail to provision. 

Ideally the script would auto-select the region and then create all resources in a "try-catch" block design pattern. If any exceptions occur it would then automatically roll back the resources and move on to the next region (until a fully successful provisioning occurs).
