### ISSUE TITLE
Lab 1 - Role of PowerShell script

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#142]
Regarding 

![image](https://user-images.githubusercontent.com/1765732/170262462-af331e70-9ae4-4487-af45-ba4b763d54b4.png)

This script is in fact focused on uploading files to the data lake.

**Comment by TheJamesHerring** [comment]
Updated to reflect more clearly what script 2 data is utilized for within labs
