### ISSUE TITLE
Extra lab prerequisites

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#143]
After the PowerShell script was split into several components extra pre-requisites / dependencies were introduced into the labs. These should be reflected in the instructions. This is especially so for PowerShell script 2, which now runs in Lab 1. Examples:

In lab 2:

> Before starting this lab, ensure you have successfully completed the setup steps to create your lab environment.

This lab in fact also requires running the PowerShell script in Lab 1. Similarly for Lab 4. 

Please review other lab instructions for the same issue.

**Comment by TheJamesHerring** [comment]
We'll be running a few review in next quarter, will close for now as the approach to labs will be simplified.
