### ISSUE TITLE
Lab 4 - Expected PowerShell Script error

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#144]
Since the PowerShell script were refactored the following comment should be moved from the instructions for Lab 1 to Lab 4:

> The following error may also occur and can safely be ignored: 
> 07-create-wwi-perf-sale-heap with label CTAS : Sale_Heap. Cannot index into a null array.

The comment can also be updated a bit to match the latest wording:

![image](https://user-images.githubusercontent.com/1765732/170325022-46b94c05-78f9-46a6-b9d4-0d9414e79601.png)

**Comment by TheJamesHerring** [comment]
Thanks for the catch, it's been moved.  JH
