### ISSUE TITLE
Lab 5 - SQL Pool Shutdown instructions are in previous task

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#145]
Instructions need to move back to the appropriate section:

![image](https://user-images.githubusercontent.com/1765732/170494273-a4a01ad5-1a5c-451a-9df4-b8e760cd4d84.png)

**Comment by TheJamesHerring** [comment]
Instructions for pause put back in proper location. Thank you.
