### ISSUE TITLE
Lab 5, Setup-Part03 (429) Too Many requests

### ISSUE THREAD

**Issue by BriannaOrtiz** [MicrosoftLearning/DP-203-Data-Engineer#148]
#### Step: 03

Description of issue

Half of my students are getting this error when running the setup 3:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/93536716/171422062-ff18f5dc-1178-415e-b25f-f276d2fcb4af.png)

We have tried re-running the script and in some cases deleting the Resorce group and starting from scratch

any idea on how to solve this? my students are stuck here

Many thanks in advance

**Comment by TheJamesHerring** [comment]
@BriannaOrtiz Is there a common Region involved and have you seen it this week?
