### ISSUE TITLE
Module 3: Lab 3: Exercise 2: Task 4: Notebook 3.Exercise-Deduplication-of-Data

### ISSUE THREAD

**Issue by chris-utter** [MicrosoftLearning/DP-203-Data-Engineer#149]
Execution of cells inline results in Error: Analysis Exception: Path does not exist: dbfs:/user/account/people.parquet

**Comment by craigbeeremct** [comment]
If that file doesn't exist then your answer in cmd 7 didn't work and you need to go back and fix it.

**Comment by TheJamesHerring** [comment]
Thanks @craigbeeremct : @chris-utter are you still seeing this error - ping me in teams if so and I'll take a look.  I suspect it might be something simple.

**Comment by craigbeeremct** [comment]
> If that file doesn't exist then your answer in cmd 7 didn't work and you need to go back and fix it.

Wow, looking back at this, my answer is very terse and dismissive. Sorry Chris, I should have been more helpful.
