### ISSUE TITLE
Lab 5 placeholder replacement

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#15]
There are 2 places in the instructions where the following is mentioned:

> -- Replace <PrimaryStorage> with the workspace default storage account name.

However, there is no <PrimaryStorage> placeholder to replace. I think the intent was to instruct students to replace the "SUFFIX" placeholder.

**Comment by GraemeMalcolm** [comment]
Thanks - fixed!
