### ISSUE TITLE
Lab5: Task 3: Cosmos DB Setup: Error

### ISSUE THREAD

**Issue by venkatnandim** [MicrosoftLearning/DP-203-Data-Engineer#152]
# Module: 05
#### Step: 03

Description of issue
I am getting following error when running '.\dp-203-setup-Part03.ps1' from powershell.
![image](https://user-images.githubusercontent.com/71718502/173204676-36db36aa-bcd7-450f-9f84-c6d21655c388.png)

Repro steps:

1.
1.
1.

**Comment by TheJamesHerring** [comment]
did you run .\dp-203-setup-part01.ps1 and part 02.ps1 first, there are dependencies built into these that store the resource group and service names in files for convenience.  Thanks, James H.
