### ISSUE TITLE
Semicolons

### ISSUE THREAD

**Issue by craigbeeremct** [MicrosoftLearning/DP-203-Data-Engineer#158]
It bugs me to see no semicolons at the end of any of the SQL statements. I'd really like to see them in there.

It is best practice for Microsoft SQL Server. As far as I know, it's also best practice for Microsoft's cloud database products.

I know it might look like a little thing, but I feel that training material should adhere to best practices where it can.

**Comment by TheJamesHerring** [comment]
@craigbeeremct , I'll make sure that the semicolons are included as we do regular reviews to find items like this but if you do see specific instances please let me know the specific lab and lines when you come across them and I'll be happy to address them ASAP.
