### ISSUE TITLE
Mod 00 Fixes

### ISSUE THREAD

**Issue by vasuja515** [MicrosoftLearning/DP-203-Data-Engineer#16]
-	Module 00 Deployment Script fixes – We had a number of students who ran az login, and started provisioning resources. However, even after provisioning there was a drop in connection to their Azure environment which ultimately meant the student needed to re do the entire process
o	In Module 4 we have a Connect-AzAccount and then az login, this seemed to work seamlessly in Module 00 to ensure the connection is established then doing the az login

-	Reduce dependencies between modules – A per module setup script helps here – check for necessary resources, if they exist from previous work and are set correctly, great! If not, recreate them.
o	A great example here: Module 7 is dependent on Module 6, however it mentions the datasets and resources which are being used in Module 7. There is a validation check from the student to ensure they have the necessary resources to continue with Module 7. It would be helpful to have something similar per module. 

-	Increase error checking – this can be done by:
o	Adding steps in labs to verify outputs, show debugging steps etc. This needs to happen more frequently instead of waiting until the end of the data flow.
o	Adding scripts that assist in verifying stages of progress – did they complete this task properly? Did they configure the SQLPool with the correct size? Etc

**Comment by GraemeMalcolm** [comment]
`Connect-AzAccount` is included in the script - AFAIK the order of `az login` and `Connect-AzAccount` should make no difference as long as the student logs in with the same credentials and selects the appropriate subscription.

**Comment by GraemeMalcolm** [comment]
Script is now updated, which should hopefully resolve the issues you were seeing.
The dependencies were introduced as part of the effort to reduce lab complexity and cost. We'll note your feedback and continue to monitor as the new content is adopted for a potential future refresh.
