### ISSUE TITLE
dp-203-setup-Part01.ps1 needs UserId but never set it?

### ISSUE THREAD

**Issue by MXMorrissey** [MicrosoftLearning/DP-203-Data-Engineer#161]
dp-203-setup-Part01.ps1 throws the error below:

Performing post-deployment configuration...
Granting admin@AzureSky772.onmicrosoft.com admin permissions...
Assign-SynapseRole : Cannot bind argument to parameter 'PrincipalId' because it is an empty string.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-20
3-setup-Part01.ps1:198 char:110
+ ... d "6e4bf58a-b8e1-4cc3-bbf9-d73143322b78" -PrincipalId $userId  # Work ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Assign-SynapseRole], ParameterBindingValidationExcep
   tion
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Assign-SynapseRo
   le

Assign-SynapseRole : Cannot bind argument to parameter 'PrincipalId' because it is an empty string.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-20
3-setup-Part01.ps1:199 char:110
+ ... d "7af0c69a-a548-47d6-aea3-d00e69bd83aa" -PrincipalId $userId  # SQL  ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Assign-SynapseRole], ParameterBindingValidationExcep
   tion
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Assign-SynapseRo
   le

Assign-SynapseRole : Cannot bind argument to parameter 'PrincipalId' because it is an empty string.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-20
3-setup-Part01.ps1:200 char:110
+ ... d "c3a6d2f1-a26f-4810-9b0f-591308d5cbf1" -PrincipalId $userId  # Apac ...
+                                                           ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Assign-SynapseRole], ParameterBindingValidationExcep
   tion
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Assign-SynapseRo
   Le

The script is looking for #UserId, but does n to seem to capture it anywhere.

# Add the current userto Admin roles
Write-Host "Granting $userName admin permissions..."
Assign-SynapseRole -WorkspaceName $workspaceName -RoleId "6e4bf58a-b8e1-4cc3-bbf9-d73143322b78" -PrincipalId $userId  # Workspace Admin
Assign-SynapseRole -WorkspaceName $workspaceName -RoleId "7af0c69a-a548-47d6-aea3-d00e69bd83aa" -PrincipalId $userId  # SQL Admin
Assign-SynapseRole -WorkspaceName $workspaceName -RoleId "c3a6d2f1-a26f-4810-9b0f-591308d5cbf1" -PrincipalId $userId  # Apache Spark Admin

What am I missing?

Thanks,

Michael

**Comment by ErikBoSo** [comment]
Same issue here. First error message:
az : The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spe
lling of the name, or if a path was included, verify that the path is correct and try again.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-203-setup-Part01.ps1
:16 char:1
+ az login
+ ~~
    + CategoryInfo          : ObjectNotFound: (az:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by TheJamesHerring** [comment]
updated the code, checking to see what has changed.  Thanks for notification.
