### ISSUE TITLE
spark cluster not available need to run setup1 again

### ISSUE THREAD

**Issue by erikvani** [MicrosoftLearning/DP-203-Data-Engineer#164]
# Module: 01
#### Step: 04

create cluster gives error in australia west and uksouth
cjooosing other regions succeed

Azure Quota Exceeded Exception:
Error code: InvalidTemplateDeployment, error message: The template deployment failed with error: 'The resource with id: '/subscriptions/65564499-a2de-4aec-85b2-865b4bc309c8/resourceGroups/databricks-rg-adbworkspaceam1jyps-2uuv5ic2sp37o/providers/Microsoft.Compute/virtualMachines/8b5300b5222246c6a44f585882c73199' failed validation with message: 'The requested size for resource '/subscriptions/65564499-a2de-4aec-85b2-865b4bc309c8/resourceGroups/databricks-rg-adbworkspaceam1jyps-2uuv5ic2sp37o/providers/Microsoft.Compute/virtualMachines/8b5300b5222246c6a44f585882c73199' is currently not available in location 'australiaeast' zones '' for subscription '65564499-a2de-4aec-85b2-865b4bc309c8'. Please try another size or deploy to a different location or zones. See https://aka.ms/azureskunotavailable for details.'.'.

**Comment by NFGodoy** [comment]
I had a similar problem. I believe it would be better to remove "australiaeast" from $preferred_list in line 110 of dp-203-setup-Part01.ps1 before running it again. I replaced it with "eastus". In another occasion I had an error when creating the CosmosDB resource. That happened for westeurope. The region was too busy. I replaced that with "eastus2". Now I have:
$preferred_list = "eastus","northeurope", "southeastasia","uksouth","eastus2","westus","westus2" 

Can you confirm that "uksouth" is also a problem? Not sure if guessing which regions will work or not is not a very efficient way to fix the problem. I tend to always use eastus in other courses and this is usually fine, but also fails sometimes, in which case I try westus. What makes the problem more difficult is that even if the databricks resource could be successfully created, the issue happens later when we try to create the cluster.

**Comment by erikvani** [comment]
One student had issues with uk south. I am also changing #preferredlist. Thes problem occurred in the past as well, so a check should be made before choosing a region. Same for cosmos db in setup3.

**Comment by TheJamesHerring** [comment]
If you see this for a particular class, I would change the preferred list to exclude those regions. However, don't assume each class will have that problem and continue to do it until you're sure.

**Comment by TheJamesHerring** [comment]
We will be changing these scripts in the coming weeks and months where each lab will have no dependencies on one another. As this is training, and most of the ILT students are running on sponsorship accounts, there are limitations. That said, the BYOL to the classes should run into less problems associated with regions (except those limited by administrators) which they can account for.

James H.

**Comment by molenaar** [comment]
Australia still gives this error. Workaround is to create an additional Databricks service after the running the setup script. The creation of a cluster succeeds. Databricks isn't used or isn't linked to any other lab or service.

For my students the only regions that work are West US and East US. Others fail on different places.
 
>We will be changing these scripts in the coming weeks and months where each lab will have no dependencies on one another
That would be nice.
