### ISSUE TITLE
ParseError

### ISSUE THREAD

**Issue by ivan-ds** [MicrosoftLearning/DP-203-Data-Engineer#167]
# Module: 00
#### Step: 5

I have the following error when executing the script
 ParserError: C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-203-setup-Part01.ps1:1
Line |
   1 |  <<<<<<< HEAD
     |    ~
     | Missing file specification after redirection operator.

Repro steps:

1.
1.
1.

**Comment by TheJamesHerring** [comment]
please try again with elevated permissions. Can you post a screenshot of the error as well?

**Comment by TheJamesHerring** [comment]
This was a merge error, it has been fixed.
