### ISSUE TITLE
Issue #166 was closed but the latest merge does not address the issue

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/DP-203-Data-Engineer#168]
The latest merge still leaves line 59 as: 
$userId = az ad signed-in-user show --query id -o tsv
but it should be
$userId = az ad signed-in-user show --query objectId -o tsv

**Comment by NFGodoy** [comment]
Hi James,

you can see in the screenshot that for me it has to be objectId. But you are also right as there was a change in Azure CLI 2.37.0 (https://docs.microsoft.com/nb-no/cli/azure/microsoft-graph-migration#breaking-changes) and you are certainly using a more recent version than mine. I've taken the screenshot from my own laptop, but in the VM that is provided by Skillable (aka LearnOnDemand) the Azure CLI is 2.25.0. This Lab Provider is a quite popular one not only in Australia, so I guess this issue is affecting other instructors as well. 

Thanks.
     On Thursday, 28 July 2022, 11:33:27 pm AEST, James Herring ***@***.***> wrote:  
 
 


objectId returns an empty value whereas id will return the id of the signed-in-user, I just tested this again. can you send a screenshot of what you're seeing in your message and the error it is causing?

**Comment by TheJamesHerring** [comment]
I think the move to cloud slice will alleviate this for you if you run from Vms powershell, we are currently testing this in tandem with other time-saving script optimizations.
