### ISSUE TITLE
Module : 00  dp-203-setup.psl error 

### ISSUE THREAD

**Issue by cjpark-sapcsa** [MicrosoftLearning/DP-203-Data-Engineer#17]
# Module: 00
#### Step: 00

HI Team, 

I was using my internal subscription and and got the below error.    

Anyone face the same error ? 

B. Rgds

Chan Jin 
================================
 C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation> .\dp-203-setup.ps1
Import-Module : The specified module 'Az.CosmosDB' was not loaded because no valid module file was found in any module directory.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-203-setup.ps1:3 char:1
+ Import-Module Az.CosmosDB
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Az.CosmosDB:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

WARNING: The names of some imported commands from the module 'solliance-synapse-automation' include unapproved verbs that might make them less
discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved
verbs, type Get-Verb.
Connect-AzAccount : The default context can no longer be found; please run 'Get-AzContext -ListAvailable' to see all available contexts,
'Select-AzContext' to select a new default context, or 'Connect-AzAccount' to login with a new account.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-203-setup.ps1:19 char:1
+ Connect-AzAccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

Get-AzSubscription : The default context can no longer be found; please run 'Get-AzContext -ListAvailable' to see all available contexts,
'Select-AzContext' to select a new default context, or 'Connect-AzAccount' to login with a new account.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-203-setup.ps1:20 char:9
+ $subs = Get-AzSubscription | Select-Object
+         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-AzSubscription], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.Azure.Commands.Profile.GetAzureRMSubscriptionCommand

You cannot call a method on a null-valued expression.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-203-setup.ps1:21 char:4
+ if($subs.GetType().IsArray -and $subs.length -gt 1){
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by GraemeMalcolm** [comment]
The script has been updated, and should resolve most of these issues.
The warning about the unapproved verbs in the solliance package can be safely ignored.
The Cosmos DB package is installed in the hosted VM, and the error you report is non-repro for me - are you running this in an environment other than the official hosted VM?
