### ISSUE TITLE
Obvious error/typo in \dp-203-setup-Part01.ps1

### ISSUE THREAD

**Issue by romanlykhnenko** [MicrosoftLearning/DP-203-Data-Engineer#171]
# Module: 00
#### Step: 00

Description of issue
there is this string that makes this script unfunctional.
The participants of the training cannot run the labs because of this error ! 
Maybe it would helpful to have an automated validation procedure after merge of every PR to ensure that the package runs ?

![image](https://user-images.githubusercontent.com/11474104/181599211-620415c6-c10e-4ef7-8434-b549c677a880.png)

Repro steps:

**Comment by TheJamesHerring** [comment]
removed additional lines from merge
