### ISSUE TITLE
Setup script - cannot be run more times

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/DP-203-Data-Engineer#172]
Setup script 01 is changing content of script 02 and 03. Bug in code prevent to running script more times without starting from fresh Lab environment or delete/clone scripts. This solution enables to run scripts more time.

# Solution
Instead of replace parts of script 02 and 03  use "include" scripts with parameters.

## dp-203-setup-Part01.ps1
Do not use "replace" functionality. It doesn't work. Create new file with parameter. Line 277. I found dp-203-setup-Part01.ps1 in .gitignore so I didn't create pull request. 

```
Set-Content -Path .\parameters-from-01.ps1 -Value $SetupStep2Variables
```
## dp-203-setup-Part02.ps1
"Include" script on line 12 and 13

```
# Add Values from the first setup script here
. .\parameters-from-01.ps1
```

Create parameter file for next script. Line 137

```
Set-Content -Path .\parameters-from-02.ps1 -Value $SetupStep3Variables
```

## dp-203-setup-Part03.ps1

"Include" parameters starting line 15

```
# Add Values from the first setup script here
. .\parameters-from-01.ps1

# Add Values from the second setup script here
. .\parameters-from-02.ps1
```

**Comment by ErikBoSo** [comment]
I agree - the Get-Content -replace will (at best) only work the first time, the scripts run.

**Comment by TheJamesHerring** [comment]
This script will be going away with the re-design, which is currently in final planning.
