### ISSUE TITLE
Setups scripts can't survive Lab environment crash or reset

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/DP-203-Data-Engineer#173]
If lab environment crash or reset setup script chain is broken,

# Solution

Change instruction and setup scripts to run in Azure Shell.

**Comment by TheJamesHerring** [comment]
We've been looking at this for a bit and policies can prevent proper execution from cloud shell and there are some limitations with cloud shell as well.  There is a path to alleviate each of these issues you're bringing up and I believe Anna has a meeting to discuss them.
