### ISSUE TITLE
Remove dp-203-setup-Part03.ps1

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/DP-203-Data-Engineer#174]
Add new lab activity to use [Azure Cosmos DB Data Migration Too](https://docs.microsoft.com/en-us/azure/cosmos-db/import-data) to upload data to Cosmos DB. It is already used as workaround for broken dp-203-setup-Part03.ps1.  It will give new knowledge to students and we will not maintain another script.

**Comment by TheJamesHerring** [comment]
Thanks for the suggestion, we'll take it under consideration when working on the new iteration, keeping in mind that the DE isn't typically responsible for this type of data migration and it's not part of OD, they have a requirement for integration which Synapse Link handles.
