### ISSUE TITLE
Suggestion - add information how to get password

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/DP-203-Data-Engineer#175]
# Lab 10
#### Step 11:

I suggest adding information how to get password from Key Vault or reset admin password in Synapse Analytics. Students very often forgot password they create on first day of training.

**Comment by TheJamesHerring** [comment]
Thanks for the suggestion, we'll take it under consideration in the next iteration. In the meantime, you might have them put it in notepad. JH
