### ISSUE TITLE
Script Returning Errors even after modifying script as instructed

### ISSUE THREAD

**Issue by REPhilpott** [MicrosoftLearning/DP-203-Data-Engineer#176]
Skillable Tickets raised 585278,596689, 597622.
When running the dp-203-setup-Part0.ps1 I continue to get errors, even after modifying script dp-203-setup-Part01.ps1 at line 110 with "eastasia", "northcentralus",

First Name: Russel
Last Name:
Your email Address:
Role: Student
Training Organization's Name: Microsoft
How may we help you?: I have a problem with my lab
I have a problem with my lab: My lab will not launch (start)
Lab Instance ID Number: 24838524

# Module: dp-203
#### Step: 5

Description of issue
I have run the scripts again according to the instructions from Skillable, removed the resource used for training but not the network.
At Modual 0 step 5 I edited the script as instructed jus to use "eastasia", "northcentralus".
I ran the script for the first time and all I got was errors.
[archive-1.zip](https://github.com/MicrosoftLearning/DP-203-Data-Engineer/files/9240512/archive-1.zip)

**Comment by TheJamesHerring** [comment]
Your error message denotes that you didn't use proper authentication. I would add all regions into the script to allow for more likelihood of success in creating all of the necessary components (Synapse, Databricks, CosmosDB).  This isn't a bug.
