### ISSUE TITLE
Lab 09: Incorrect instructions and Screenshots in the lab

### ISSUE THREAD

**Issue by junnhssn** [MicrosoftLearning/DP-203-Data-Engineer#177]
# Module: Lab 09: Support Hybrid Transactional Analytical Processing (HTAP) with Azure Synapse Link
#### Step: 02

Description of issue:

"Select the Linked tab and expand the Azure Cosmos DB section (if this is not visible, use the ↻ button at the top right to refresh Synapse Studio), then expand the asacosmosdb01 (CustomerProfile) linked service. Right-click the OnlineUserProfile01 container, select New notebook, and then select Load to DataFrame."

The screenshot does not match the instructions.

This is what we are seeing in our environment :
![image](https://user-images.githubusercontent.com/47213023/182851078-cbe154e2-e0de-4a25-88bf-06de6fd515bc.png)

Similarly In Lab 09: Exercise 3
Task 1
Step 8 
The name of the view is different than the one we see in the user environment. Please update the instructions and the screenshots
"OnlineUserProfile01"

"Select the Workspace tab and expand the SQL database group. Expand the Profiles SQL on-demand database (if you do not see this on the list, refresh the Databases list). Expand Views, then right-click the UserProfileHTA view, select New SQL script, and then Select TOP 100 rows"

![image](https://user-images.githubusercontent.com/47213023/182853163-834c30ab-4663-463a-ab3d-0275ceba37af.png)

Please update this.
Thanks and Regards.

**Comment by TheJamesHerring** [comment]
@junnhssn this is related to the other bug you opened and I do have it on my list in DevOps. I'll leave this open for visibility and close the related one.

**Comment by TheJamesHerring** [comment]
These instructions were designed for a ILT (Instructor Led Training) course which has a preconfigured machine. Very happy you found it: try this link for the AZ Module installation and make sure to check your versions of PS.  https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-8.2.0
