### ISSUE TITLE
Lab 09: Exercise 1: Unable to find the cosmos_db_htap container

### ISSUE THREAD

**Issue by junnhssn** [MicrosoftLearning/DP-203-Data-Engineer#178]
# Module: Lab 09: Support Hybrid Transactional Analytical Processing (HTAP) with Azure Synapse Link
#### Step: 03

Description of issue
Unable to find the cosmos_db_htap container in the environment. The setup was completed successfully.
![image](https://user-images.githubusercontent.com/47213023/182849634-5a630430-ccc2-4263-9853-ff754d1bf3b6.png)

I am able to complete the exercise without the container. Please clarify.

Thanks and Regards.

**Comment by TheJamesHerring** [comment]
Closing as it's part of the same bug and already in DevOps.
