### ISSUE TITLE
Latest commit to dp-203-setup-Part1.ps1 will cause error if the AZ client is the latest one.

### ISSUE THREAD

**Issue by NFGodoy** [MicrosoftLearning/DP-203-Data-Engineer#179]
The choice between objecId and id on line 58 depends on which version of the AZ Client is installed.  When I opened the issue #166 I asked to change from id to objectId, but at that time the Skillable (aka LearnOnDemand) VM and my own laptop were using an older version of the AZ Client. The issue #166 was closed and id remained.  Assuming the majority of the lab environments will be using a recent version as well, we should stick to id:
So, line 58 should be 
 $userId = az ad signed-in-user show --query id -o tsv 

NOTE: LODS changed for a short time to id, but then reverted back to objectId. So, for the time being those who are using LODS should stick to objectId. But eventually we all will be using a more recent version of az cli.

**Comment by TheJamesHerring** [comment]
Yes @NFGodoy this has proven to be tricky; although in my latest testing, the objectId for forward looking work appears to be the appropriate call. I will look at adding code that looks for the current cli and changing the --query item to a variable.  I will also make some notes in the directions. I'll leave this open until that is complete or at least consistent on platforms.

**Comment by saiiitkgp713** [comment]
Thank you @NFGodoy. Like you mentioned, i am also using the latest version of azure-cli.  Changing from "objectID" to "id" (case senesitive - have to be in small letters) worked for me.

**Comment by annav88** [comment]
I think we can close this bug, as it is not always reproducible and there is a suggested workaround by NFGodoy and James
