### ISSUE TITLE
ps script error >> New-AzStorageContext : Cannot validate argument on parameter 'StorageAccountName'. 

### ISSUE THREAD

**Issue by vho123** [MicrosoftLearning/DP-203-Data-Engineer#181]
# Module: 05
#### Step: 03

Description of issue
ps script throw many errors.

first Error message:
New-AzStorageContext : Cannot validate argument on parameter 'StorageAccountName'. The argument is null or empty. Provide an argument
that is not null or empty, and then try the command again.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-203-setup-Part03.ps1:33 char:61
+ ... New-AzStorageContext -StorageAccountName $dataLakeAccountName -Storag ...
+                                              ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzStorageContext], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorageCon
   text

**Comment by TheJamesHerring** [comment]
@vho123 are you still having this problem and did you run the scripts in order? this appears to be a problem with the parameters that are stored at the end of Script 2 $dataLakeAccountName and passed on for dp-203-setup-Part3.ps1 to read.

**Comment by vho123** [comment]
@TheJamesHerring  Yes, i discovered the part 3 script require values returned from part 1 and part 2 script. And the script did not passed in correct value into part 3. it's weird.
I removed everything, re-run from lab 1 to lab 5, it works finally but wasted so much azure credit.

**Comment by TheJamesHerring** [comment]
@vho123 I'm sorry to hear about the wasted credit. we're working to change the labs to where much fewer credits will be used at one time. do you have an MSDN subscription through work or were you just using a Free Trial?
James H
