### ISSUE TITLE
Lab 9 instructions

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/DP-203-Data-Engineer#182]
# Module: 9
#### Step: 2,  4/5

Description of issue

HTAP container no longer needs to be mentioned in the instructions or utilised in the notebooks due to change in May 31. When individuals sync their stores, in step 3, using the OnlineUserProfile01, it eliminates the need for a HTAP container.  Only purpose of it now is to demonstrate how to enable an analytical store from the creation of cosmosDB container. 

Repro steps:

1.  Change any reference from HTAPOnlineProfile to OnlineUserProfile01 in Synapse notebooks
- Screenshot shared in step 4

1.  Remove any reference of HTAP in lab 9 instructions. 
`In this segment, we will use built-in gestures in Synapse Studio to quickly create a Synapse Notebook that loads data from the analytical store of the HTAP-enabled container, without impacting the transactional store.`

#### Step: 8

- Screenshot at step 8 (Select the Workspace tab and expand the SQL database group. Expand the Profiles SQL on-demand database (if you do not see this on the list, refresh the Databases list). Expand Views, then right-click the UserProfileHTA view, select New SQL script, and then Select TOP 100 rows.) does not match previous sql code for view (e.g. view name is now: OnlineUserProfile01)

**Comment by chris-utter** [comment]
![DP-203 Lab 9 Correction](https://user-images.githubusercontent.com/67066583/188011097-5319d816-6636-4dbe-92b8-26e256944cfc.png)

**Comment by msft-agahgnango** [comment]
![image](https://user-images.githubusercontent.com/88350767/189524262-fe73d3bd-b20c-49a1-922e-cbf1c5477e5a.png)
Please also remove reference to UserProfileHTAP in the Exercise 2- Task 1 -Step 4 as well.

**Comment by TheJamesHerring** [comment]
merged updates
