### ISSUE TITLE
Lab 10 connection string not available in authentication mode step 11

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/DP-203-Data-Engineer#183]
# Module: 10
#### Step: 11

Description of issue
Authentication mode options : Managed Identity or SQL server authentication. Not connection string
Repro steps:

1. Change authentication mode to SQL server OR managed identity. 
1. Update image to reflect change related to Synapse Dedicated SQL Pool
1.

**Comment by TheJamesHerring** [comment]
merged updates
