### ISSUE TITLE
Lab 6: Change in Synapse UI - drop "select Array of Documents" in JSON settings

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/DP-203-Data-Engineer#184]
# Module: 06
#### Step: 07

Description of issue

`JSON Settings: select Array of documents `
There is no longer a drop down for selecting an array of documents in JSON settings in the synapse interface under source options when building the `user_profiles_to_datalake` pipeline.  

See image
![image](https://user-images.githubusercontent.com/104829457/190335854-a59d06fb-6a53-4509-b1e5-f566cc4ec55e.png)

Repro steps:

1. Remove this action
1. Keep other configurations (e.g. Wildcard paths + Select Array of documents for Document form

**Comment by annav88** [comment]
This is not really a bug, because the text instruction clearly stated already what has to be done, but we added a screenshot for inattentive readers, so that it is visible what to select.
