### ISSUE TITLE
Add (more) intermediate json representations of the pipeline/data flow to help people along if something went wrong.

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/DP-203-Data-Engineer#188]
# Module: 06
## Lab/Demo: 06

Description of issue
Small mistakes can take a long time to find and fix. Changes in the interface are impossible to keep up with for the lab instructions. I notice students struggling with pipeline labs in general due to these two issues. 

Possibly helpful solution:
In every lab where a pipeline/data flow is built, provide a couple of intermediate solutions (and a final one) in json. 'If you get stuck in the following part, you can skip ahead by changing the json to the following', or something along those lines.

**Comment by annav88** [comment]
You could create the MDF in your env and have the json definition either published in your Github account (and share with students if they are stuck) or simply have JSON files and send them the file for the full MDF in labs 5/6.
