### ISSUE TITLE
change wording in Lab 9 

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/DP-203-Data-Engineer#189]
# Module: 09
#### Step: 05

Description of issue
Not a bug but something that confuses students in my classroom
`Paste the following SQL query. In the OPENROWSET statement, replace YOUR_ACCOUNT_NAME with the Azure Cosmos DB account name and YOUR_ACCOUNT_KEY with the Azure Cosmos DB Primary Key from the Keys page in the Azure portal (which should still be open in another tab).`

Note: the account key and primary key do not exist in another tab due to changes in instructions (it's gotten much better! :) ) . Please make it more explicit where students can find these details.

Repro steps:
Put instructions down to where students can find the cosmosDB account key and primary key 
1. Key: in cosmos db -> keys -> primary key can be found
1. Account: name of cosmosDB account (can be found in overview as a header) 
![image](https://user-images.githubusercontent.com/104829457/191691511-d48110fa-ee41-4f6d-aa4f-ce3115be7485.png)

**Comment by TheJamesHerring** [comment]
Will take a look at this when re-writing instructions. Thanks for the recommendation.
