### ISSUE TITLE
Module 10 - Extra "Lab details" entry in TOC

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#19]
The entry does not go anywhere. Please remove.

**Comment by VitalyMCT** [comment]
Likewise for Module 7. Please review the other labs for the same issue.

**Comment by GraemeMalcolm** [comment]
It actually takes you to the current section
(We're considering removing these TOC sections anyway)

**Comment by VitalyMCT** [comment]
Sorry, can you please clarify on "current section" in this context? I click the link and nothing happens.

Agreed, perhaps it's best to remove the TOC altogether.
