### ISSUE TITLE
Password hint is wrong and causes student frustration

### ISSUE THREAD

**Issue by boomalator** [MicrosoftLearning/DP-203-Data-Engineer#191]
# Module: All
## Lab/Demo: All

The "password hint" listed on the logon screen of the VM is totally wrong. Yes, on Skillable/LODS, the correct password is listed in "resources", but that doesn't stop students from trying the wrong password for 25 minutes. Makes for a bad student experience and wastes everyone time.

The "hint" should be removed if it can't be corrected.

Repro steps:

1. Lock the VM
2. Enter a bad password and attempt to log in
3. Click okay on the "Password is incorrect" message
4. Observe fictitious incorrect password hint.

**Comment by TheJamesHerring** [comment]
Please open a ticket within the lab environment (skillable).

**Comment by boomalator** [comment]
I did. Skillable said it’s a Microsoft issue.


Mobile: big fingers, little buttons, and don't get me started about autocorrect.

On Oct 5, 2022, at 8:49 AM, James Herring ***@***.***> wrote:

﻿

Please open a ticket within the lab environment (skillable).

**Comment by TheJamesHerring** [comment]
If you're speaking of the VM image of Windows itself, there should be no instance where a student is using a "hint" to obtain a password that is available in the resources. This is something as an MCT that you should address at the start of class, ie., through the demonstration of the resources tab in the learning content.

**Comment by boomalator** [comment]
I do not think that the correct response to a documented error in the lab image is to instruct the MCT to instruct the students to ignore the incorrect information presented in the lab.

The resources tab is correct. The VM image has an error. (It would be better to leave the hint blank or perhaps have the hint say “see resources tab”.)

Yes, students “should” do everything the designer and instructor expect and always act logically. However, a large number of students, especially in ESI classes, appear to be human and act on their own accord, sometimes without even telling the instructor.

Last week, a student spent 25 minutes trying to log on with the password displayed on the hint. By the time he asked for help, he was frustrated and angry, and asking if he could leave the class and rebook.

I don’t like customers/students having that experience.

Let me ask this another way:
  What is the benefit of leaving wrong information in the lab?


On Oct 5, 2022, at 8:56 AM, James Herring ***@***.***> wrote:

﻿

If you're speaking of the VM image of Windows itself, there should be no instance where a student is using a "hint" to obtain a password that is available in the resources. This is something as an MCT that you should address at the start of class, ie., through the demonstration of the resources tab in the learning content.

**Comment by TheJamesHerring** [comment]
Let's meet in the middle. the current images will be replaced very soon and I'll confirm that this is fixed when Azure Pass goes away from the labs (very, very soon).

**Comment by boomalator** [comment]
Thank you.
