### ISSUE TITLE
Lab 4 - 2 types of errors when running PowerShell script

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#194]
There are 2 types of errors that always come up in that particular script and this confuses the students. 

Both types were previously documented in the lab instructions. Somehow during refactoring of a single setup script into multiple scripts that are in individual labs the corresponding notes disappeared from the instructions.

Here's the 1st type of errors: https://github.com/MicrosoftLearning/DP-203-Data-Engineer/issues/144

I see at least two possible solutions:

1) Ideal: change the scripts so there are no errors. Every time there is a script error in the classroom students get concerned, even if we tell them that they are expected. This would also make the scripts look more polished.

2) Less ideal: restore the comments in the instructions that reassure the students the 2 types of errors are unexpected. This is not great because students are new to these scripts. This would require them to parse out all the errors, looking for unexpected ones vs the "real" ones they need to fix, thus making their classroom experience needlessly complicated and time consuming. The scripts in this lab setup are already quite error-prone, so any increase in robustness would be beneficial to the student experience.

**Comment by VitalyMCT** [comment]
A related issue is with the instructions for Lab 7, which currently state:

>Setup warnings that you can safely ignore:
>The following error may also occur and can safely be ignored: > 07-create-wwi-perf-sale-heap with label CTAS : Sale_Heap. Cannot index into a null array.

Those instructions are also out of date. There is no setup script in that lab that can throw those errors.

**Comment by TheJamesHerring** [comment]
We're currently re-writing a great deal of these labs to be independent of one another with a target of 12/31. This should resolve a number of issues and will be easier to manage costs and troubleshoot. We'll address this one in the coming weeks.
