### ISSUE TITLE
Lab 8 - Incorrect instruction

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#195]
See step in screenshot below. The text says to create a parameter, whereas the screenshot says to create a variable. The screenshot is correct.

![image](https://user-images.githubusercontent.com/1765732/194551641-6d7312b9-f45f-45c7-ae16-59735923ccc4.png)

**Comment by TheJamesHerring** [comment]
Great catch, change is made, will push this week. JH
