### ISSUE TITLE
Lab Setup for Lab 1

### ISSUE THREAD

**Issue by mikegrant5** [MicrosoftLearning/DP-203-Data-Engineer#198]
# Module: 00
#### Step: 00

Description of issue
Lab 1 Setup Script fails 
Repro steps:
(i)     The lab VM uses AZ Client 2.25, whereas the latest Azure Client is 2.42 
With 2.25 it uses ‘objectID’ whereas with later versions it is ‘id’
this means that the powershell script must be altered to use ‘id’ if using a later client as otherwise the PrincipalID has a null or empty value and fails.
(ii)    The other main issue was harder to figure out, but it is actually the “Location” used in the script:
if running the lab from Europe, the first PowerShell script has:
# Select a random location that supports the required resource providers
# (required to balance resource capacity across regions)
Write-Host "Selecting a region for deployment..."
 
$preferred_list = "australiaeast","northeurope", "southeastasia","uksouth","westeurope","westus","westus2"
 
If you leave it as above then the script fails, but if you change it to
$preferred_list = "eastus","eastus2","westus"
 
Then it works perfectly
 
So this explains why running the script from the USA works but not from Europe.
 
Finally registering the Resource Providers needs to be done before the script is run, because registering the providers does take time and the script will error if the providers have not finished registering.
 

1.
1.
1.

**Comment by TheJamesHerring** [comment]
This has been a continuing issue but should be resolved in the upcoming release. If I get some cycles, I will modify the code; however, I have verified that the internal MTTs are aware of the regional differences.
