### ISSUE TITLE
Module 2: 2020-writers becomes 2019-writers

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/DP-203-Data-Engineer#199]
# Module: 02
#### Step: 01

Description of issue
In the description of exercise 2, there are multiple mentions of 2020 and a group tailwind-2020-writers. However, in the rest of the lab, you are creating tailwind-2019-writers. This is explained right before step 1 of task 1, but still a bit confusing. Why not adjust the preceding explanations to 2019?

Also, the explanation right before step one says "However, our data set ends in 2019, so we will create a tailwind-2019-writers group instead of 2021." If you decide to keep this instead of updating the explanation, you need to change that 2021 to 2020.

**Comment by TheJamesHerring** [comment]
This will be modified in the Jan release
