### ISSUE TITLE
Deploy to Azure button link to non-existent .json file

### ISSUE THREAD

**Issue by markfitzqa** [MicrosoftLearning/DP-203-Data-Engineer#2]
# Module: 00FullSetupREADME.md
#### Step: 01

Description of issue
Deploy to Azure button is linked to Chris Testa-O'Neils github library that is now empty.  This needs to be changed to "https://github.com/MicrosoftLearning/DP-203-Data-Engineer/blob/master/Allfiles/00/artifacts/environment-setup/automation/00-asa-workspace-core.json"

Repro steps:

1. Access the lab, click the button and get an error.

**Comment by ctesta-oneillmsft** [comment]
This should be addressed with the current setup. Thanks for the feedback Mark

**Comment by markfitzqa** [comment]
The markdown still has "    

<a href="https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2Fctesta-oneillmsft%2Fxyz%2Fmain%2FAllfiles%2F00%2Fartifacts%2Fenvironment-setup%2fautomation%2F00-asa-workspace-core.json" target="_blank"><img src="https://aka.ms/deploytoazurebutton" /></a>"

Links back to your github not the course repository.

**Comment by GraemeMalcolm** [comment]
Looks like **00FullSetupREADME.md** still need to be updated.

**Comment by ctesta-oneillmsft** [comment]
it is removed, as we cannot guarantee to support this on local machines
