### ISSUE TITLE
Lab 9 (HTAP): Cosmos account key and account name instructions missing

### ISSUE THREAD

**Issue by douwevandenberg** [MicrosoftLearning/DP-203-Data-Engineer#200]
# Module: 09
#### Step: 05

Description of issue
"Paste the following SQL query. In the OPENROWSET statement, replace YOUR_ACCOUNT_NAME with the Azure Cosmos DB account name and YOUR_ACCOUNT_KEY with the Azure Cosmos DB Primary Key from the Keys page in the Azure portal (which should still be open in another tab)."

The instructions that used to come earlier in the lab have been removed, so that azure portal tab is not open and students don't know where to find the key (or which key they need).

**Comment by TheJamesHerring** [comment]
looking into this.
