### ISSUE TITLE
Lab5, Task 3, point 3, dp-203-setup-Part03.ps1

### ISSUE THREAD

**Issue by Rozenceto** [MicrosoftLearning/DP-203-Data-Engineer#201]
# Module: 00
#### Step: 3

Description of issue
PS script does not ask for the subscription or resource group to which to execute the script. Get the 1st one subscription that is found and execute. If there is more than one subscription then the execution failed.

**Comment by TheJamesHerring** [comment]
Can you post a screenshot - the script is designed to prompt if multiple subscriptions and I verified it works. Thanks, JH
