### ISSUE TITLE
Lab 5 - Setup Script 3

### ISSUE THREAD

**Issue by Jason-M-Richards** [MicrosoftLearning/DP-203-Data-Engineer#204]
# Lab: 05
### Task: 03

The instruction state that this script takes 10-15 minutes. I have not run into a case where that is true - it takes 35-40 minutes in my experience. Can we update the instructions?

<img width="321" alt="image" src="https://user-images.githubusercontent.com/46732841/206034064-07935f1d-5c57-430f-8c60-44683da040da.png">

**Comment by TheJamesHerring** [comment]
This has been updated in the next lab push in January.
