### ISSUE TITLE
Module 00: Lab environment setup - Error geting UserId by ObjectId 

### ISSUE THREAD

**Issue by mrvluiz** [MicrosoftLearning/DP-203-Data-Engineer#205]
# Module: 00
#### Step: 00

Description of issue
I found some problems during my course when running the first script file named dp-203-setup-Par01.

by the way I noticed that the $UserId from script that we running on PowerShell are getting empy values and them the fully script get failure.

I found an article on microsft that "**objectId**" was changed by only "**id**"
https://learn.microsoft.com/nb-no/cli/azure/microsoft-graph-migration

I make the changes on the file and the script works well now retrivieving my userId

Repro steps:

1.
![image](https://user-images.githubusercontent.com/19996435/206606557-afafad54-ad05-494c-aea0-2b3ab9de897e.png)

2.
![image](https://user-images.githubusercontent.com/19996435/206606582-ed6c66fe-7c4c-44b9-a4c2-20ef8faf12a2.png)

**Comment by suketunayak** [comment]
![image](https://user-images.githubusercontent.com/12823966/207228159-3201bc8f-89db-482e-b21b-13bc7bc8757d.png)
 **I also noticed that the $UserId from script that we running on PowerShell are getting empy values and them the fully script get failure.**

**Comment by TheJamesHerring** [comment]
This is a regional and version issue on the GRAPH API being distributed globally. We will change this once we have confirmed that all regions use GRAPH.
James H.
