### ISSUE TITLE
Lab6 - Task 2 - step 2  renaming of cosmos linked service reference to match updated name in Synapse(LOW PRIORITY)

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/DP-203-Data-Engineer#206]
# Module: 06
#### Step: 02

Description of issue
Minor issue- students became confused as lab mentions "Azure Cosmos DB (SQL API)" but synapse has since renamed to "Azure CosmosDB for No SQL " and wanted to know which one to use. 

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/104829457/208887290-9b6d5c30-0221-4734-934d-af4d0f615384.png)

Repro steps:

1. Change Azure CosmosDB(SQL API) to Azure CosmosDB for No SQL
1. Update the image to the one shared in the file. :)

**Comment by TheJamesHerring** [comment]
@VEshelbyMTT thanks Victoria for your continued contributions - we will be archiving this after the next release and I encourage you to continue to list these changes to Azure which cause training issues as they arise.  JH
