### ISSUE TITLE
Launch Workspace Sign in Error

### ISSUE THREAD

**Issue by J-O-S-H-C** [MicrosoftLearning/DP-203-Data-Engineer#207]
# Module: 00
#### Step: 02

Description of issue
Using Launch Workspace button throws a login error: 
Your account LabUser-27765230@LODSPRODMSLEARNMCA.onmicrosoft.com does not have Owner or Contributor role on the Databricks workspace resource in the Azure Portal, which is required to "Launch Workspace." If your admin has already added you to this workspace, click "Sign in" above. Otherwise, please ask your administrator to grant you access or add you as a [user directly in the Databricks workspace](https://docs.microsoft.com/azure/databricks/administration-guide/users-groups/users).

![image](https://user-images.githubusercontent.com/39581053/208940987-c72c9c5e-5805-442e-b4b0-5e36bd86db90.png)

Two option for repair:
1.) Updating instructions to use the "URL" field instead of the Launch Workspace button.
![image](https://user-images.githubusercontent.com/39581053/208941367-62dff317-a729-4895-8db1-dc72d865085d.png)
2.) Fixing the permissions error so the LOD account will appropriately login no matter the route student's take.

**Comment by VEshelbyMTT** [comment]
This is a common issue with cloud slice: 

Here's the fix to the launch workspace: 

![image](https://user-images.githubusercontent.com/104829457/209169949-3ba14abc-dc57-48f6-b5ac-01a19833add1.png)
![image](https://user-images.githubusercontent.com/104829457/209169975-7da8d764-2a94-4c71-a502-4df50f2b3a84.png)
![image](https://user-images.githubusercontent.com/104829457/209170004-f3c269f8-db15-49a8-aa54-0742b8a900c9.png)
![image](https://user-images.githubusercontent.com/104829457/209170026-5d7e2406-790b-4ddd-8502-5f910a5763a5.png)


Hope it helps! :)

**Comment by TheJamesHerring** [comment]
This is actually due to cloudslice and I'll check on the hyperlink notes, as they were included in the scripts when we were testing the move from Azure Pass. 
JH

**Comment by VitalyMCT** [comment]
This is still an issue as of this week. I asked Skillable to add a note to the instructions for their Cloud Slice variant of the labs, to direct students to use workaround number 1 proposed by @J-O-S-H-C  above. They've just added the note this morning. 

Also, I recommend that for tracking purposes to only close issues in this repo if they are actually resolved. That's the GitHub standard. The current approach to just closing seemingly all the issues makes it needlessly challenging for MCTs to know what's outstanding, results in duplicate issues, etc.

Finally, if anyone is wondering about why some MCTs are seeing Cloud Slice and some are not: DP-203 is on Cloud Slice for special Microsoft events such as ESI. General audience events remain on Azure Pass for now. I did not see this explained anywhere, so thought to mention it for community's benefit.

**Comment by TheJamesHerring** [comment]
I closed this issue because it was resolved in cloud slice, some time ago using a warning, which is easier than walking through a security update. The warning message appears as: "Due to a known UI issue, please use the URL provided above the "Launch Workspace" button (beneath the Managed Resource Group identifier) and NOT the button itself as it will cause a permissions error to be displayed." Please let me know if you're not seeing this message in the cloudslice lab.  JH

**Comment by VitalyMCT** [comment]
The workaround (i.e. that note) was only added this morning, after my specific request to Skillable to do so. My request was filed yesterday. 

Please feel free to reference ticket 824061 at Skillable. It may be worth investigating what other Cloud Slice -specific issues are still outstanding, if any.

**Comment by TheJamesHerring** [comment]
I don't have access to skillable content and they don't have access to update this repository. I'll reach out to them when they return from the holiday, but this is a transient issue nonetheless. Thanks for your contributions, and this has been added back to the correct repository.
JH
