### ISSUE TITLE
Lab 7 Ex 1, Task 1 Step 3 - check OnlineUserProfile01 container

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-203-Data-Engineer#209]
# Module: 07
#### Step: 03

Description of issue
Instructions and portal screenshot need updating, as we do not have cosmos_db_htap as stated in current instructions nor UserProfileHTAP (as shown in current image)
Repro steps:
![image](https://user-images.githubusercontent.com/11367710/209166908-2b5e5788-f7a7-4daf-a22e-c17868483eb2.png)

We only have OnlineUserProfile01 container.  
change as follows:
3. In the left-hand menu, select Azure Synapse Link. a. Ensure Account enabled is set.
b. Under Enabled Azure Synapse Link for your containers make sure **OnlineUserProfile01 is** selected.
![image](https://user-images.githubusercontent.com/11367710/209171385-173bc21d-2d98-4ca6-9785-fdea66ef98eb.png)

**Comment by TheJamesHerring** [comment]
This is a known issue and will be addressed in the next release coming soon - this repository will be archived in the coming quarter. Thank you all for your continued support and contributions to this and other repositories! JH
