### ISSUE TITLE
Module 1 - Markdown issue

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#21]
Screenshot: 

![image](https://user-images.githubusercontent.com/1765732/130339443-449cbea2-879b-41e7-b240-e51e5e862f13.png)

**Comment by GraemeMalcolm** [comment]
Screenshot from where? The hosted VM?

**Comment by VitalyMCT** [comment]
It's direct from GitHub, i.e. https://github.com/MicrosoftLearning/DP-203-Data-Engineer/blob/master/Instructions/Labs/LAB_01_compute_and_storage_options.md

I would imagine ALHs would have similar rendering.

**Comment by GraemeMalcolm** [comment]
What exactly is the issue you're seeing in the rendered page?

**Comment by VitalyMCT** [comment]
The one in the screenshot :) The Markdown is not rendered properly. Take a look on the linked page and you will see it right away. It's just impacting that small segment of Markdown.

**Comment by GraemeMalcolm** [comment]
Thanks. Fixed!

**Comment by VitalyMCT** [comment]
Perfect, thank you.
