### ISSUE TITLE
Error during dp-203-setup-Part03.ps1 script deployment

### ISSUE THREAD

**Issue by ralsouza** [MicrosoftLearning/DP-203-Data-Engineer#210]
# Module: 05: Ingest and load data into the data warehouse
#### Step: 3

I got these errors during the script execution:
`Invoke-RestMethod: {"code":"ExpiredAuthenticationToken","message":"Token Authentication failed with SecurityTokenExpiredException - IDX10223: Lifetime validation failed. The token is expired. ValidTo: '1/11/2023
12:10:56 AM', Current time: '1/11/2023 12:16:03 AM'."}
Invoke-RestMethod: {"code":"ExpiredAuthenticationToken","message":"Token Authentication failed with SecurityTokenExpiredException - IDX10223: Lifetime validation failed. The token is expired. ValidTo: '1/11/2023
12:10:56 AM', Current time: '1/11/2023 12:16:04 AM'."}
Invoke-RestMethod: {"code":"ExpiredAuthenticationToken","message":"Token Authentication failed with SecurityTokenExpiredException - IDX10223: Lifetime validation failed. The token is expired. ValidTo: '1/11/2023
12:10:56 AM', Current time: '1/11/2023 12:16:05 AM'."}
Invoke-RestMethod: {"code":"ExpiredAuthenticationToken","message":"Token Authentication failed with SecurityTokenExpiredException - IDX10223: Lifetime validation failed. The token is expired. ValidTo: '1/11/2023
12:10:56 AM', Current time: '1/11/2023 12:16:06 AM'."}
Invoke-RestMethod: {"code":"ExpiredAuthenticationToken","message":"Token Authentication failed with SecurityTokenExpiredException - IDX10223: Lifetime validation failed. The token is expired. ValidTo: '1/11/2023
12:10:56 AM', Current time: '1/11/2023 12:16:07 AM'."}`

Repro steps:
1. Open the cloud shell
2. Navigate to \dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\
3. Run the script .\dp-203-setup-Part03.ps1

**Comment by ralsouza** [comment]
Is there another one to study?

**Comment by TheJamesHerring** [comment]
Sure, the new content labs are posted below the archive message: https://github.com/MicrosoftLearning/DP-203-Data-Engineer

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
