### ISSUE TITLE
Issue with the environment setup automation script "00-asa-workspace-core.json"

### ISSUE THREAD

**Issue by junnhssn** [MicrosoftLearning/DP-203-Data-Engineer#212]
# Module: Environment Setup 
### File name: 00-asa-workspace-core.json

Description of issue
The ASA workspace deployment fails with the following error message. The issue occurs intermittently. Can you please look into this and check if any changes are required to the script?

{
    "status": "Failed",
    "error": {
        "code": "MessagingGatewayConflict",
        "message": "<Error><Code>409</Code><Detail> TrackingId:a3fee0f2-7a61-4126-995f-948b566c1ac8_G2, SystemTracker:eventhub845671.servicebus.windows.net:$tenants/eventhub845671, Timestamp:2023-01-25T09:29:08</Detail></Error>"
    }
}
![image](https://user-images.githubusercontent.com/47213023/214531372-9ce4b7d0-5851-4007-bb20-beca72b62ea3.png)

Thanks and Regards,
Junaid Hussian.

**Comment by TheJamesHerring** [comment]
This repository has been officially retired.
