### ISSUE TITLE
Repository question

### ISSUE THREAD

**Issue by Kiyani1** [MicrosoftLearning/DP-203-Data-Engineer#213]
Hi all,

Just got 2 questions in mind.

1. Which repository should the lab hosters be using for the course DP-203?

2. What is the difference between this repository and the one in the link below:
https://github.com/MicrosoftLearning/dp-203-azure-data-engineer

Any help will be greatly appreciated thanks!

**Comment by Derekp20** [comment]
The link you give is for the new repository. The DP-203 Exam changes on 6 Feb 2023. The new repository has labs that match the new content. At the moment Lab providers seem to be using the Old repository. Hopefully they will change very soon! If your delegates have two screens they can use an existing hosted lab and open the Gitgub version of the new lab instructions.

**Comment by Kiyani1** [comment]
Thank you for the clarification!
