### ISSUE TITLE
Azure Cosmos DB (SQL API) doesn't exist for linked service

### ISSUE THREAD

**Issue by dtarek1** [MicrosoftLearning/DP-203-Data-Engineer#214]
# Module: 06
#### Step: 02 Open Linked services and select + New to create a new linked service. Select Azure Cosmos DB (SQL API) in the list of options, then select Continue.

Description of issue: Azure Cosmos DB(SQL API) doesn't appear in the options list. 

Repro steps:

1.
1.
1.

**Comment by Derekp20** [comment]
Need to use Cosmos DB (NoSQL API). The opposite to what students expect causing confusion!

**Comment by TheJamesHerring** [comment]
This repository has not been officially retired.
