### ISSUE TITLE
Lab 9, running setup script.

### ISSUE THREAD

**Issue by VEshelbyMTT** [MicrosoftLearning/DP-203-Data-Engineer#217]
# Module: 04
#### Step: 05

` cd dp-203/Allfiles/labs/09
 ./setup.ps1`

Description of issue
Suspend-AzSynapseSQLPool not loaded from module
![image](https://user-images.githubusercontent.com/104829457/234258234-c159b674-3a15-4c20-a370-6c2be0a6c0be.png)

Might be worth investigating.

**Comment by TheJamesHerring** [comment]
these labs are retired.
