### ISSUE TITLE
LAB_01_compute_and_storage_options.md

### ISSUE THREAD

**Issue by azuredevops619** [MicrosoftLearning/DP-203-Data-Engineer#218]
# Module: 01
#### Step: 03

Description of issue
%run "./Includes/Classroom-Setup"  fails to mount wasbs://training@dbtraineastus.blob.core.windows.net/ as the SAS token given in Dataset-Mounts file is expired. 

Repro steps:

1. Execute %run "./Includes/Classroom-Setup"  part of 11-Delta-Lake-Architecture.dbc

Kindly provide the SAS token or updated https://github.com/MicrosoftLearning/DP-203-Data-Engineer/raw/master/Allfiles/microsoft-learning-paths-databricks-notebooks/data-engineering/DBC/11-Delta-Lake-Architecture.dbc file

**Comment by TheJamesHerring** [comment]
This set of labs is retired.
