### ISSUE TITLE
Module 8 - "Resouce naming throughout this lab" section

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#23]
This section appears to be obsolete in that resource naming in the actual lab does not follow the convention described. I think the simplest fix would be to simply remove this section. Please confirm.

![image](https://user-images.githubusercontent.com/1765732/130339569-7c7a2f90-c475-4aa9-a119-a38724baadf4.png)

**Comment by GraemeMalcolm** [comment]
Agreed - removed!
