### ISSUE TITLE
Module 4 - Making "Potential errors that you can ignore" section more promiment.

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#27]
If I may make a suggestion - perhaps this section can be linked to, made inline or otherwise referenced before or as the students run the PS command? 

Students naturally perform the instruction steps in order. So when the PS command throws errors then think something is wrong. i.e. they did not get to the section that says errors are normal, as it's downstream in the instructions. Thank you.

**Comment by GraemeMalcolm** [comment]
Reformatted to be part of the note
