### ISSUE TITLE
Module 5 - Dependency on SQL pool  that's created in Module 4

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#28]
The labs for most modules in this course are independent, however, there is a dependency between the Dedicated SQL pool's creation in Module 4 and the use of this pool in Module 5.

This dependency is not currently highlighted, so students who skip Module 4 would get confused. I think this dependency should be noted in the Module 5 lab's pre-requisites to eliminate the confusion.

The same applies to all subsequent modules that use SQLPool01.

**Comment by GraemeMalcolm** [comment]
Thanks - fixed
