### ISSUE TITLE
Module 0 Additional Costs optimizations

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/DP-203-Data-Engineer#29]
# Module: 00
#### Step: 00

Description of issue
To save costs I made the following changes to the **00-asa-workspace-core.json** ARM template 
It might help for students and teachers trying to save costs on their own Azure Subscription. All modules run fine with these modification.

Changes/additions:

Synapse Analytics - SQL/Spark Pools
Line 28. "sqlServerSKU": "DW100c"
Line 32. "sparkMinNodeCount": "1",

Note: you can also reduce the min and maxnode counts with

```
sp='SparkPool01'
ws='asaworkspaceYOURSUFFIX'
rg='data-engineering-synapse-YOURSUFFIX'
az synapse spark pool update --name $sp --workspace-name $ws --resource-group $rg --min-node-count=0
```

Eventhub - From Standard to Basic
Line 442.  "name":"Basic"
Line 443.  "tier":"Basic",

Cosmos DB Free Tier optin (extra lines)
Line 345. "enableFreeTier": true,
Line 346.  "enableAnalyticalStorage": false,
Line 347. "analyticalStorageConfiguration": {},

Streaming Analytics  (no ARM solution found)
Configure->Scale -> Move streaming units from 3 to 1  and save

**Comment by VitalyMCT** [comment]
@molenaar, this is an excellent set of changes. 

Have you had a chance to measure the performance impact of the switch of SQL Pools to the DW100c tier?

**Comment by molenaar** [comment]
No, not yet. Its not that I'm waiting for hours. It must be minutes. For me its a waist of credits that after spinning up my SQL Pool its doing nothing, just waiting until you reach the point to perform a query or enter new data. 

I also prefer one of the Standard machines in Databricks as a cluster:
D2_v3 (14 GB) 0.75 cts/hr or F4 (8GB) 0.50 ct/hr. 

If a student want to practice with another cluster with Premium Disks or more Power, feel free after the course. I want to end up with enough credits after finishing class. Upcoming weeks I also need my subscription for other Azure Classes.

**Comment by GraemeMalcolm** [comment]
Thanks for these suggestions.
We'll need to test the labs end-to-end with these before committing to them, and ensure we get the desired balance of cost-optimization vs performance/reliability. I'll update here on what we find.
