### ISSUE TITLE
Microsoft Online Services Sign-In Assistant for IT Professionals RTW link wrong

### ISSUE THREAD

**Issue by markfitzqa** [MicrosoftLearning/DP-203-Data-Engineer#3]
# Module: 00
#### Step: bullet 4 - 

Description of issue
The link is invalid.  The 64bit version of Microsoft Online Services Sign-In Assistant for IT Professionals RTW is now "https://download.microsoft.com/download/7/1/E/71EF1D05-A42C-4A1F-8162-96494B5E615C/msoidcli_64bit.msi."

Repro steps:

1.  Access the lab, click the link and get 404 error.

**Comment by ctesta-oneillmsft** [comment]
This is no longer available,

The new setup address this issue and there is a dedicated VM

**Comment by markfitzqa** [comment]
For those going it alone the link should be changed.

**Comment by GraemeMalcolm** [comment]
Looks like **00FullSetupREADME.md** instructions need to be updated.

**Comment by ctesta-oneillmsft** [comment]
it is removed, as we cannot guarantee to support this on local machines
