### ISSUE TITLE
Module 4 Incorrect # of files

### ISSUE THREAD

**Issue by vasuja515** [MicrosoftLearning/DP-203-Data-Engineer#31]
# Module: 04
#### Step: 06

"There are 31 files in the folder, one for each day of the month. These files were imported by a temporary process to account for an issue with Tailspin's import process. Let's now take a few minutes to explore some of the files."

With the new script we have 3 files imported into the file system

**Comment by GraemeMalcolm** [comment]
Thanks, fixed!
