### ISSUE TITLE
Module 7 - Screenshot mismatch

### ISSUE THREAD

**Issue by saramashfej** [MicrosoftLearning/DP-203-Data-Engineer#32]
# Module: 07
#### Step: 05

Description of issue
There is a mismatch between the screen shot provided and the instructions, it says in the instructions "Under the General tab, set the Name to **user_profiles_to_datalake**" While the screenshot shows **"write_user_profile_to_asa"**
Repro steps:
![image](https://user-images.githubusercontent.com/10104033/130661838-106e04bd-7c03-45ba-9699-23dd22aa922a.png)

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
Thanks. I've set aside time at the end of this week to work through the backlog of issues and will respond here after I've investigated.

**Comment by GraemeMalcolm** [comment]
Thanks - fixed!
