### ISSUE TITLE
Module 4 - Use of sqlanalytics() is deprecated

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#33]
According to the Product Group the use of this function is deprecated. From https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/synapse-spark-sql-pool-import-export:

> Warning: The sqlanalytics() function name has been changed to synapsesql(). The sqlanalytics function will continue to work but will be deprecated. Please change any reference from sqlanalytics() to synapsesql() to prevent any disruption in the future.

I would recommend adjusting the code in the lab instructions to use the new function.

**Comment by GraemeMalcolm** [comment]
Thanks. I've set aside time at the end of this week to work through the backlog of issues and will respond here after I've investigated.

**Comment by GraemeMalcolm** [comment]
Thanks - fixed!
