### ISSUE TITLE
Module 4 - Performance of preview with column headings from CSV

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#34]
Regarding 

>In the preview dialog, you have to option to turn off the With column header option. As it appears this file does not contain column headers, set this to off and inspect the results.

My students are reporting today that Synapse Analytics is very slow on this step. Apparently it's taking a few minutes to complete.

If you could repro this, perhaps a note about expected timing could be added to the instructions?

**Comment by GraemeMalcolm** [comment]
Thanks. I've set aside time at the end of this week to work through the backlog of issues and will respond here after I've investigated.

**Comment by GraemeMalcolm** [comment]
I added a warning this step can take some time
