### ISSUE TITLE
Module: 03 Slide 13 PPT typo: dropDupicates should be dropDuplicates 

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-203-Data-Engineer#35]
# Module: 03 Slide 13
#### Step: 00

Description of issue
PPT typo, module 3, slide 13, dropDupicates should be dropDuplicates  (missing the letter l)
Repro steps:
![image](https://user-images.githubusercontent.com/11367710/130688658-03b916f1-abfa-47ef-892c-efdd556f2013.png)

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
Thanks. Since this is non-blocking, we'll update in the next refresh of the instructor materials.

**Comment by ctesta-oneillmsft** [comment]
Update made and will be published this friday
