### ISSUE TITLE
Using "IF NOT EXISTS" leaves students unable to repeat steps or correct steps

### ISSUE THREAD

**Issue by sthoward0914** [MicrosoftLearning/DP-203-Data-Engineer#36]
# Module: 5
#### Step: 04 and 06

The T-SQL scripts in both of these steps present the same type of problem for students who make a mistake and try to re-run them. In both cases, if they change anything, or anything happens wrong, and they try it again, it will just not create the object because they use "IF NOT EXISTS ..." This stumped a few students in class today (although I'll grant you I'm not sure how they managed to do it that way.) 

To avoid this problem, please modify the script to use the positive case like this example:

IF  EXISTS (SELECT * FROM sys.workload_management_workload_classifiers WHERE [name] = 'HeavyLoader')
BEGIN
    DROP WORKLOAD CLASSIFIER HeavyLoader
END

CREATE WORKLOAD Classifier HeavyLoader WITH
(
        Workload_Group ='BigDataLoad',
        MemberName='asa.sql.import01',
        IMPORTANCE = HIGH
);

SELECT * FROM sys.workload_management_workload_classifiers

When done like this, it doesn't matter if they've run it before, and it doesn't matter if they messed it up. Running it again will simply drop what was incorrectly created and they can create the object anew.

**Comment by VitalyMCT** [comment]
I agree. If the scripts could be adjusted to be safely re-runnable it would alleviate a common source of issues for the students. 

The same applies to some of the Spark-based code that's also running in other labs. I am currently using it as a lesson to explain troubleshooting & interpreting error messages, however, avoiding errors with defensive coding would be ideal IMO.

**Comment by GraemeMalcolm** [comment]
Thanks. I've set aside time at the end of this week to work through the backlog of issues and will respond here after I've investigated.

**Comment by GraemeMalcolm** [comment]
OK, fixed (I consolidated the scripts into a single script, since you need to drop the classifier before the group if recreating them)
