### ISSUE TITLE
Module 7 Incorrect Screenshot

### ISSUE THREAD

**Issue by vasuja515** [MicrosoftLearning/DP-203-Data-Engineer#37]
# Module: 07
#### Step: 05

Screenshot of Pipeline says write_user_profile_to_asa. The instructions mention to rename the pipeline to user_profile_to_datalake

**Comment by GraemeMalcolm** [comment]
So the real problem here is an over-reliance on screenshots. I've removed this one because it's not really necessary (we should likely go through the labs and thin the number of screenshots to include only ones where the UI is potentially confusing)

**Comment by GraemeMalcolm** [comment]
Fixed
