### ISSUE TITLE
Github repository clone wrong github library

### ISSUE THREAD

**Issue by markfitzqa** [MicrosoftLearning/DP-203-Data-Engineer#4]
# Module: 00
#### Step: 01

Description of issue
Download instruction to download the repository points to the old repository (chris-o'neill..) should be replaced with:

git clone https://github.com/MicrosoftLearning/DP-203-Data-Engineer

Repro steps:

1.  Run the code

**Comment by ctesta-oneillmsft** [comment]
Hi Mark,

the updated instructions in the repo should address this now

**Comment by markfitzqa** [comment]
The instructions still refer to your github:

1. Open a PowerShell Window as an administrator, run the following command to download the artifacts

    ```powershell
    mkdir c:\dp203

    cd c:\dp203

    git clone https://github.com/ctesta-oneillmsft/xyz data-engineering-ilt-deployment
    ```

**Comment by GraemeMalcolm** [comment]
@ctesta-oneillmsft , I don't think your update made it though - 00FullSetupREADME.md still references your personal repo, and the last merge in the repo is mine from 8 days ago.

**Comment by ctesta-oneillmsft** [comment]
00FullSetupREADME.md is to be removed. We cannot guarantee to support the setup on peoples local machines that are subject to unknown configurations
