### ISSUE TITLE
Conserving Dedicated SQL Pool usage

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#40]
I think there is an opportunity to optimize the instructions around this, to make the best use of the Azure credit possible. This can be done, by simply shifting pool activation and deactivation closer to the lab areas where it's required.

For example, in Module 8, the pool is only used in Exercise 3, whereas it's activated in Exercise 0. This means that it's running needlessly for Exercises 1 and 2.

This approach will both save credits during the course and illustrate best practices around efficient practices to the students.

**Comment by GraemeMalcolm** [comment]
We've reduced the size of the pool, so hopefully credit conservation is less of an issue.
