### ISSUE TITLE
DP203 Handbook (older content in Agenda Objective for Module 10-17)

### ISSUE THREAD

**Issue by jarougha** [MicrosoftLearning/DP-203-Data-Engineer#41]
# Module: 10-17 notes in Agenda Objective in the MOC instructor handbook
#### Step: Starting Page 6

Description of issue
Older content for Module 10-17 in Handbook and Module 10,11 need title and content change In Agenda Objective section on page 6: 

**What it is now.......**

Module 10: Optimize Query Performance with Dedicated SQL Pools in Azure Synapse
                                Module 11: Analyze and Optimize Data Warehouse Storage
                                Also include previous content and Module 13-17

**What is needs to be - Repro steps:**
Module 10 Real-time Stream Processing with Stream Analytics 
Module 11 Create a Stream Processing Solution with Event Hubs and Azure Databricks
Change Objective and content to new content
Remove 13-17

Please ignore if this is already been raised.

Kind Regards
Jane

**Comment by ctesta-oneillmsft** [comment]
Thanks 

The update is in progress and will be published next week
