### ISSUE TITLE
Module 4, Lab 4 Task 2 Step 3 Running .\setup-sql.ps1 causes an error. 

### ISSUE THREAD

**Issue by jarougha** [MicrosoftLearning/DP-203-Data-Engineer#42]
# Module: 04
#### Step: 03

Running .\setup-sql.ps1 causes an error. 

PS C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation> .\setup-sql.ps1
.\setup-sql.ps1 : The term '.\setup-sql.ps1' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:1
+ .\setup-sql.ps1
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\setup-sql.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation>

Repro steps:

1.
1.
1.

**Comment by GraemeMalcolm** [comment]
Ensure you've cloned the latest version of the repo
