### ISSUE TITLE
Module 7 Incorrect Integration Dataset Names

### ISSUE THREAD

**Issue by vasuja515** [MicrosoftLearning/DP-203-Data-Engineer#43]
# Module: 07
#### Step: 00

In the pre-requisites we create a linked service and two integration data sets. The naming is incorrect and gives a schema error when pulling the json script into the Mapping Data Flow: 
CosmosDB Integration Dataset should be: asal400_customerprofile_cosmosdb
ADLS Integration Dataset should be: asal400_ecommerce_userprofiles_source
![image](https://user-images.githubusercontent.com/77507719/131721536-806b3dca-0cdf-4d34-8fbb-042c377bc7a5.png)

**Comment by GraemeMalcolm** [comment]
Fixed.
