### ISSUE TITLE
Archive https://github.com/MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure?

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#45]
Suggestion: perhaps the old repo for this course can be made read-only for clarity? 

I often end up navigating there (from Google, browser history, etc.) and it sometimes takes some time to realize the content has moved. Perhaps other MCTs and maybe ALHs are in the same boat.

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository/archiving-repositories

**Comment by ctesta-oneillmsft** [comment]
The old repository is being left

**Comment by VitalyMCT** [comment]
@ctesta-oneillmsft  It would really help if a little bit of explanation is provided when constructive feedback from MCTs is discarded by closing issues they invested time in opening.
