### ISSUE TITLE
incorrect code in instructions

### ISSUE THREAD

**Issue by Derekp20** [MicrosoftLearning/DP-203-Data-Engineer#46]
# Module: 07
## Lab/Demo: 07
##Ex 2
#### Step: 05

The modified code in italics is incorrect:
abfss://wwi-02@asadatalakexxxxxxx.dfs.core.windows.net/top-products/.parquet*.

it should be:
abfss://wwi-02@asadatalakexxxxxxx.dfs.core.windows.net/top-products/*.parquet

The image shows the code correctly with the * before .parquet

**Comment by ctesta-oneillmsft** [comment]
Thanks. this is resolved
