### ISSUE TITLE
Lab 10 - References to Power BI

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#49]
> In this task, you will configure Stream Analytics to use the event hub you created as a source, query and analyze that data, then send it to Power BI for reporting and aggregated data to Azure Synapse Analytics.

This reference is from a pre-July 30th version of this lab. Power BI is no longer in scope for this lab. I think it should thus be removed.

There is another reference to Power BI in the instructions that could probably also be removed.

**Comment by ctesta-oneillmsft** [comment]
Its a passing reference that POwer could be used here, and not instrumental to the lab

**Comment by VitalyMCT** [comment]
@ctesta-oneillmsft That's not what the instructions say. The instructions say "you will ... send it to Power BI", which this lab no longer does. It's a factual error in the instructions. As such, students get confused when they see it.

**Comment by GraemeMalcolm** [comment]
Re-opening to address the concern that there's an explicit statement implying students will use Power BI in the lab

**Comment by ctesta-oneillmsft** [comment]
All references to Power BI removed
