### ISSUE TITLE
Integrating feedback from MCTs from original DP-203 repo

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#5]
For the labs that remain in this new version of DP-203, can all feedback provided via GitHub issues at https://github.com/MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure please be actioned in this new repo?

**Comment by ctesta-oneillmsft** [comment]
some have, some have not due to the removal of content.

**Comment by VitalyMCT** [comment]
Some have been missed. 

Example: https://github.com/MicrosoftLearning/DP-203T00-Data-Engineering-on-Microsoft-Azure/issues/132
