### ISSUE TITLE
Virtual Machine setup instructions

### ISSUE THREAD

**Issue by aashish-jha** [MicrosoftLearning/DP-203-Data-Engineer#50]
# Module: 00
#### Step: 00

Description of issue
I want to practice the labs in my own Azure Subscription that I have but I don't know the requirements for the Virtual Machine setup needed for the labs. Can someone please guide me on that?

Repro steps:

1.
1.
1.

**Comment by ctesta-oneillmsft** [comment]
I'm afraid we can only provide support for courses that use the VM
