### ISSUE TITLE
Module 0 - Lab setup error

### ISSUE THREAD

**Issue by cts286996** [MicrosoftLearning/DP-203-Data-Engineer#51]
# Module: 00
#### Step: 5

Description of issue: Azure login is not prompted. Not able to run the setup script. Kindly help troubleshoot. I followed the steps mentioned.

Repro steps:
PFB error in Power shell script

Import-Module : The specified module 'Az.CosmosDB' was not loaded because no valid module file was found in any module
directory.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-203-setup.ps1:2
char:1
+ Import-Module Az.CosmosDB
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (Az.CosmosDB:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

WARNING: The names of some imported commands from the module 'solliance-synapse-automation' include unapproved verbs
that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again
 with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Sign into Azure using your credentials..
az : The term 'az' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-203-setup.ps1:16
char:1
+ az login
+ ~~
    + CategoryInfo          : ObjectNotFound: (az:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Now sign in again to allow this script to create resources...
Connect-AzAccount : The term 'Connect-AzAccount' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-203-setup.ps1:20
char:1
+ Connect-AzAccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Connect-AzAccount:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Get-AzSubscription : The term 'Get-AzSubscription' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\dp-203\data-engineering-ilt-deployment\Allfiles\00\artifacts\environment-setup\automation\dp-203-setup.ps1:22
char:9
+ $subs = Get-AzSubscription | Select-Object
+         ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-AzSubscription:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
1.
1.
1.

**Comment by cts286996** [comment]
Issue was with Az modules not installed. Its fixed

**Comment by saiiitkgp713** [comment]
Hey, I'm having the same problem and wasn't able to run the scripts. The lab instructions specified using a virtual machine. i have installed a VM using virtual box and tried to implement the lab instructions in that VM.  I got the same errors as you mentioned and wasn't able to find a solution. I don't know how to install the az modules which you have specified int eh comment section. I would highly appreciate any help in this regard.

**Comment by TheJamesHerring** [comment]
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-8.2.0

**Comment by saiiitkgp713** [comment]
Thank you for the link. it really helped me in resolving the errors.

**Comment by cts286996** [comment]
Hey Sai Anvesh,

Install Azure Powershell module. That should be enough.

Regards,
Manojhari
