### ISSUE TITLE
Module 2 Lab, Exercise 2, Task 5 - Screenshots vs. text

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#53]
Please check the following step:

> In Synapse Studio, in the Data hub, on the Linked tab select the Azure Data Lake Storage Gen2/asaworkspacexxxxxxx/wwi02 container; and in the sale-small/Year=2016/Quarter=Q4/Month=12/Day=20161231 folder, right-click the sale-small-20161231-snappy.parquet file, select New SQL script, and select Select TOP 100 rows.

The screenshot points to 2019 instead. Which one to use?

**Comment by ctesta-oneillmsft** [comment]
resolved

**Comment by ludurr** [comment]
I am lab only `sale-small/Year=2016/Quarter=Q4/Month=12/Day=20161231`  container parquet not the reference within Instructions:   `sale-small/Year=2019/Quarter=Q4/Month=12/Day=20191231`
