### ISSUE TITLE
Module 00: Lab environment setup

### ISSUE THREAD

**Issue by juriaan-atos** [MicrosoftLearning/DP-203-Data-Engineer#54]
# Module: 00
#### Step: 00

Description of issue
Login failed of the initial sertup script 
The reason is the the flag - Devicecode was missing
When i added the flag the script run ok.
(I don't know if this is an error on my side or a change in the module Connect-AzAccount)

Repro steps:
1. LINE 20 Connect-AzAccount 

FIX: Add Connect-AzAccount -DeviceCode

**Comment by juriaan-atos** [comment]
Bug 2: 
Description: I get an error when running the setup script (module 00: 
-> Resulting JSON is truncated as serialization has exceeded

**Comment by ctesta-oneillmsft** [comment]
I am unable to repro this issue, and we have had hundreds of interations of the setup script running without a -Device code request as far as I am aware. Therefore I am assuming this setup is not being run on the VM that is provided, so therefore closing
