### ISSUE TITLE
Verification Error Module 03

### ISSUE THREAD

**Issue by berkenbrack** [MicrosoftLearning/DP-203-Data-Engineer#6]
# Module: 03
#### Very last step

Description of issue

Verification step results in an error, despite prior steps working without an issue.  

Screenshot of the issue:

![image](https://user-images.githubusercontent.com/35786030/127983886-5799cf41-8bc8-43d9-b641-14c4507f695e.png)

Brought to our attention during testing.

**Comment by GraemeMalcolm** [comment]
Looks like the previous step hasn't completed - I bet if you re-run after a minute or so it works.
Suggest validating that hypothesis and adding a note to that effect.

**Comment by berkenbrack** [comment]
Thank you very much Graeme. Will get this to our tester.

**Comment by ctesta-oneillmsft** [comment]
That is correct. You need to wait for the command to be completed as per the messages in the cells
