### ISSUE TITLE
Module 4, Lab 4, lab setup, Task 1, Step 3 - remove Geo-redundant option

### ISSUE THREAD

**Issue by TammySmithMCT** [MicrosoftLearning/DP-203-Data-Engineer#61]
# Module: 04
#### Step: 03

Description of issue
Due to portal drift, Geo-redundant option is no longer available

Repro steps:
![dp-203-lab4-lab setup-task1-step3-remove Geo-redundant option](https://user-images.githubusercontent.com/11367710/138927977-2af8907a-d6cb-4b20-af73-3ea0fd39156a.PNG)

Update step 3 instructions and image, to that shown below:
In the Create dedicated SQL pool page, enter SQLPool01 (You must use this name exactly as displayed here) for the pool name and then set the performance level to DW100c (move the slider all the way to the left).

![dp-203-lab4-lab setup-task1-step3-remove Geo-redundant option (2)](https://user-images.githubusercontent.com/11367710/138928832-5075bee0-636a-409b-bce7-0b79f7a55ee0.PNG)

.

**Comment by GraemeMalcolm** [comment]
(I suggest just removing the images - the written instructions should be sufficient for this level of user, and the dependency on images causes issues for maintenance and localization.)

**Comment by ctesta-oneillmsft** [comment]
resolved
