### ISSUE TITLE
Module 5: Count of records incorrect

### ISSUE THREAD

**Issue by vasuja515** [MicrosoftLearning/DP-203-Data-Engineer#62]
# Module: 05
#### Task: 02 Step: 8
and
#### Task: 03 Step: 04

Description of issue "You should see a result of 4124857."

Fix: The result equals 5591630

**Comment by ctesta-oneillmsft** [comment]
I am unable to reproduct that after rerunning the labs this morning
the result is 4124857

![image1](https://user-images.githubusercontent.com/33545180/140726115-c0d559da-a683-43fd-bc42-ef1ed0d5e254.png)
