### ISSUE TITLE
Module 09 CosmosDB HTAP / Azure Synapse Link

### ISSUE THREAD

**Issue by markfitzqa** [MicrosoftLearning/DP-203-Data-Engineer#63]
# Module: 09
## Lab/Demo: 09
All

DP-203 CosmosDB HTAP (module 9)
--------------------------------------------
Firstly found that a previous CosmosDB with Azure Synapse Link had reduced options inside Synapse Studio as if the Azure Synapse Link was not enabled inside CosmosDB:

![pic1](https://user-images.githubusercontent.com/36226388/141281072-610d3f2c-6303-4eeb-a3ee-fed0431ce250.png)

This seemed strange as the CosmosDB shows as enabled for Azure Synapse link in the features:

![pic2](https://user-images.githubusercontent.com/36226388/141281114-6916e808-40ab-47a3-bc96-7f3004d98b0a.png)

There seems a new setting has now appeared under Integrations that says that short-term capacity constraints mean that although the first features setting is enabled, Azure Synapse Link for your containers needs to be requested.  This would take between 1 and 7 days to authorise.  The request button changes to Registration Pending once clicked.

![pic3](https://user-images.githubusercontent.com/36226388/141281167-d33d0a25-07ff-4c80-8747-271c4474d85e.png)

I cannot find any information on this issue on the Azure support sites.  I am on UK South.  The Azure Status page has not got any reported issues, so I assume that this will be a planned restriction.

Added: delegates found UK South, North Europe, Australia East, West US2 and Central US also restricted.

Fitz

**Comment by markfitzqa** [comment]
Hi @ctesta-oneillmsft 
Seems the delegates are having a different but related issue instead in some regions.  The CosmosDB is not created on about half the tries on my course this week with a message about high demand in the region.

![cosmosDB_fail_script](https://user-images.githubusercontent.com/36226388/142986775-d826db15-8bca-4f1d-80f1-da4a5e7a2408.png)

With this error later parts of the script that reference cosmos DB fails.  The only fix we have is running the script again.

Another issue a couple of delegates found which is strange is that the SQL password seems not to like special characters at5 the start or in some case end of the password such as @WH234WFG or 8745adefst!.  Weird but nothing we can really do about it apart from advise the delegates.  Again this fails the SQL installation parts, with the delegates running the script again to fix.

Fitz

**Comment by VitalyMCT** [comment]
Same issue with CosmosDB for some of my students yesterday. Also in "centralus" region.

**Comment by ctesta-oneillmsft** [comment]
Thanks for the additional information @markfitzqa , we are still investigating on our side

**Comment by markfitzqa** [comment]
For a quick fix if the CosmosDB is not created using the script from day 1.

1. Copy the name of the existing failed CosmosDB account if it exists and the delete it to start fresh.
2. Create a new CosmosDB with the original name.
3. Create a new CosmosDB database using the name CustomerProfile.
4. Create a new container withthin the CustomerProfile database with the following settings:
  - Container Name : OnlineProfile01
  - Scaling: Manual @ 10000 RUs
  - Partition key: /userId
5. Once container exists upload json files from the Allfiles\wwi-02\online-user-profiles-01 within the github clone subforlders.  The delegates successfully performed the lab after importing the user Id bucket 001 and 002.

Fitz

**Comment by GraemeMalcolm** [comment]
Thanks for continuing to troubleshoot this.
Longer term, I think I'm going to refactor the setup to remove the Cosmos DB creation/population in Lab 0 and do it JIT when it's needed in subsequent labs (either via a dedicated script or manually as described above). Hopefully by separating this from the rest of the setup, we'll avoid maxing out the resources and improve stability.

**Comment by molenaar** [comment]
Isn't it possible to modify the script so you can rerun the setup and it picks up, were it left before?
Or create a separate Cosmos script?
I noticed a few student with the same problem. However the KeyVault also wasn't completely configure, so only recreating Cosmos DB wasn't sufficient.

**Comment by GraemeMalcolm** [comment]
We're actively working on refactoring the script. Stay tuned!

**Comment by VitalyMCT** [comment]
It would be great if this could be prioritized high & resolved. 

Running a large event today and those for whom the script selects "centralus" are all impacted.

**Comment by MOC-Labs-Review** [comment]
MOC-Labs-Review did not encounter this issue while running the course.

**Comment by markfitzqa** [comment]
> MOC-Labs-Review did not encounter this issue while running the course.

Did you try to run the script using Azure Vouchers.  As an official MS account it is unlikely to be restricted.

**Comment by akshayytondak** [comment]
I think the lab setup part required modification, I'm also hitting with error many times & cosmos DB is a costly service it consumes most of the credit.

**Comment by TheJamesHerring** [comment]
New Scripts are out, looking forward to easing some of this although the randomness of the region will still exist to prevent over-allocating resources.
