### ISSUE TITLE
Module 04 Sparkpool

### ISSUE THREAD

**Issue by berkenbrack** [MicrosoftLearning/DP-203-Data-Engineer#7]
# Module: 04
#### Step: 05-06

Description of issue

With no running jobs in the sparkpool and everything else stopped, spark pool will not run because it advises it is requesting too many cores (screenshot below):

![image](https://user-images.githubusercontent.com/35786030/127984238-5c017599-b7bb-4085-b739-9d2f17b6f24c.png)

Work-around: sparkpool can be scaled up and steps can be completed, may be a note added to the instructions in case users run into this issue.

**Comment by ctesta-oneillmsft** [comment]
Module 4, Exercise 1, Task 3, step 5 clearly states that you must click on the stop session button on the far right hand side of the toolbar to release the Spark cluster for the next exercise.

Your error is occuring as this command has be missed
