### ISSUE TITLE
.\dp-203-setup.ps1 stuck after successful pipeline run

### ISSUE THREAD

**Issue by Agazoth** [MicrosoftLearning/DP-203-Data-Engineer#77]
# Module: 00
Setup lab

Description of issue
.\dp-203-setup.ps1 stuck  at line 418

Repro steps:

run `.\dp-203-setup.ps1`

The Synapse pipeline completes but the script does not pick that up. After 2 hours I broke the execution and ran the rest of the script (reduced DTU) by hand.

![image](https://user-images.githubusercontent.com/15127301/144738717-3c09cc33-6910-4d86-9b5e-10c856fa4b15.png)

**Comment by ctesta-oneillmsft** [comment]
Hi @Agazoth, we are seeing this in issue #63 and are currently working to adapt the setup scripts to prevent this error, please follow issue #63 for updates to resolve this.

As a result I am closing this as a duplicate issue of #63
