### ISSUE TITLE
Errors in setup in module 0 : COSMOS DB is not getting deployed

### ISSUE THREAD

**Issue by azurearchitect786** [MicrosoftLearning/DP-203-Data-Engineer#78]
# Module: 00
#### Step: 00

Description of issue

The setup script in module 0 setup is auto-selecting the region and as a consequence, deployment of cosmos DB is failing in the region of high demand.

 "status": "Failed",    "error": {        "code": "ServiceUnavailable",        "message": "Database account creation failed. Operation Id: 013dad6d-9227-4ac2-acb1-c991342d2845, Error : Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.\r\nActivityId: 5e66d57a-c558-44a1-b1ba-1a1c3e90d194, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0"    }}

**Comment by ctesta-oneillmsft** [comment]
Thanks for the feedback, please follow issue #63 that has the same problem.
