### ISSUE TITLE
Module 2 varchar(8000) exceeds max allowed

### ISSUE THREAD

**Issue by vasuja515** [MicrosoftLearning/DP-203-Data-Engineer#79]
# Module: 02
## Lab/Demo: 02
Exercise: 01
#### Step: 04

In the CREATE EXTERNAL TABLE statement, in the [TransactionId] varchar(8000), 8000 exceeds the max allowed. If kept at 4000 then the code works fine
![image](https://user-images.githubusercontent.com/77507719/145888930-5e97402e-b164-4ac8-b807-a0b318796a1f.png)

**Comment by ctesta-oneillmsft** [comment]
Thanks. I added a statement to change 800 to 4000
