### ISSUE TITLE
Issues Reported

### ISSUE THREAD

**Issue by berkenbrack** [MicrosoftLearning/DP-203-Data-Engineer#8]
# Module: 04 
#### Step: 16 

Description of issue:  There are only 3 files in the folder, nothing else to preview. 

# Module: 06
#### Step: 8 (7)

 
![image](https://user-images.githubusercontent.com/35786030/128098590-e0b12bf0-b7a4-46e8-80cb-ac6d244261b8.png)

Tester advised that publishing was not possible without adding the staging linked service and folder.  They were able to proceed by adding the datalake and pre-existing staging folder. 

# Module 7
#### Step 7

Tester advised that publishing was not possible without adding the staging linked service and folder.  They were able to proceed by adding the datalake and pre-existing staging folder.

**Comment by ctesta-oneillmsft** [comment]
Did they run the full setup in module 0?

I have run this again this morning with no issues with the setup or the instructions in the labs

**Comment by berkenbrack** [comment]
Closing issue.  Have not received additional reports of this nature since initial review. Thank you for reviewing.
