### ISSUE TITLE
Lab 2 - Azure reverted from Storage Browser to Storage Explorer

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/DP-203-Data-Engineer#82]
Our students today ran into a rather strange issue where their Azure Storage Accounts are showing the older Storage Explorer (Preview) UI, instead of the newer Azure Storage Browser (Preview) UI. This is more than just a different label, it also changes the way functionality in Exercise 2, Task 4 is accessed. 

Preliminary analysis showed that it's not a simple regional rollout difference. For example, 2 ADLS Gen2 resources, both in East US, were showing up different UIs (one Storage Explorer, one Storage Browser). The UI selection may be somehow controlled at account or subscription level.

This may require an in-depth investigation with Storage Account Azure Support to get to the bottom of and resolve. Example of the old UI showing up today:

![image](https://user-images.githubusercontent.com/1765732/146841303-78290d9e-3986-42de-9f2a-3bf960634819.png)

**Comment by VitalyMCT** [comment]
And this morning it's showing Storage Browser (Preview), for the very same resources. So Azure Portal seems to be switching back and forth between the 2 UIs. Worth digging deeper into.

**Comment by VitalyMCT** [comment]
@TheJamesHerring This class was just over a month ago. We did not try the Azure Preview Portal.

**Comment by TheJamesHerring** [comment]
Please let me know if you see this again and thanks for the update!  JH
