### ISSUE TITLE
Lab 4 setup script

### ISSUE THREAD

**Issue by bechynsky** [MicrosoftLearning/DP-203-Data-Engineer#84]
# Module: 04
#### Step: 01

Description of issue
It looks there are missing modules for SQL server if you run it as administrator. 

Repro steps:
Run script as administrator
Run script as user

Suggestion
Add task after Task 1: Close administrator Powershell and open Powershell as standard user.

**Comment by TheJamesHerring** [comment]
Please re-check after 1/28/2022, the scripts have changed, let me know if this is still repeated and I will look at your suggestion.  I did not see the issue when I ran tests this week.
