### ISSUE TITLE
Azure Data Engineer [DP-203] lab setup

### ISSUE THREAD

**Issue by akshayytondak** [MicrosoftLearning/DP-203-Data-Engineer#85]
# Module: 00
#### Step: 00

Description of issue

I am trying to do azure data engineering [DP-203] lab on my azure account but I have to do Lab environment setup with a pre-installed virtual machine but I don't have a pre-installed virtual machine so how can I do this lab setup by creating a VM in my azure account without getting any error.

Repro steps:

1.
1.
1.

**Comment by TheJamesHerring** [comment]
You would need to create a VM of a Windows Client (These Windows client images are exclusively available to Visual Studio subscribers. These "clean OS-only" images allow you to easily and quickly set up an environment in Azure to develop and test applications.) then add some additional tools such as SQL Data Explorer, then you should be able to complete from Module 00 setting up the environment.  You could also run it from your local machine as well, if you have administrative rights; however, that would be your call.  Let me know if you have any other questions.  Best, JH
