### ISSUE TITLE
Module 0 Lab setup: Central US region

### ISSUE THREAD

**Issue by saramashfej** [MicrosoftLearning/DP-203-Data-Engineer#86]
# Module: 00
#### Step: 00

Description of issue
Is it possible to remove the "centralus" region from the preferred list of regions when we run the Powershell setup script? Anytime a  script automatically  selects this region, the learner sees a lot of error especially when creating Cosmos DB. We usually remove it manually for every learner but it would save a lot of time if it was completely removed from the script for now, until capacity issues have been resolved. 

Repro steps:

1. Force setup scipt to create resources in Central US by removing other regions from the preferred region list 
1.
1.

**Comment by TheJamesHerring** [comment]
@saramashfej I will be publishing new scripts to resolve some loading issues and will review this request prior to publishing.

**Comment by TheJamesHerring** [comment]
After reviewing this request further the random distribution of regions was chosen as the best design to prevent over-allocating resources in a single or few regions for training.
