### ISSUE TITLE
lab 4 - dedicated sql pool is missing schema 

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [MicrosoftLearning/DP-203-Data-Engineer#87]
# Module: 00
#### Step: 02

Description of issue

the code snippet includes the line 

```
df.write.synapsesql("SQLPool01.wwi.TopPurchases", Constants.INTERNAL)
```
which tries to create a database in the dedicated sql pool `SQLPool01` under schema `wwi`.

Execution oft his code fails, as the schema is missing.

Repro steps:

1. Do as described in the step.

I'm not sure where the schema creation should be put, or how to best do it.

**Comment by valentin-krasontovitsch** [comment]
lab5: more missing schemas to report - wwi_staging  + wwi_perf, where the latter should have the table Sale_Heap

it seems like the same commit as in #88 is responsible (4d839861e02006fc07185385f3c7b03ae4ba62f7) - the wwi_perf and related sql scripts are still present, but are no longer called in any of the setup scripts

**Comment by TheJamesHerring** [comment]
setup-sql.ps1 has been added to the appropriate location to create schema, logins, users, etc. thanks for the catch community.
