### ISSUE TITLE
linked services missing

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [MicrosoftLearning/DP-203-Data-Engineer#88]
# Lab/Demo: 05
#### Step: 04

Description of issue

The described linked service cannot be found 

It seems 4d839861e02006fc07185385f3c7b03ae4ba62f7 deleted the creation of the linked services from the automation script `Allfiles/00/artifacts/environment-setup/automation/dp-203-setup.ps1` when splitting it up into 3 different parts.

**Comment by TheJamesHerring** [comment]
This has been updated to run the 2nd script in the appropriate location (after Databricks and prior to Synapse pyspark queries)
