### ISSUE TITLE
Module 0 lab set up instructions

### ISSUE THREAD

**Issue by sunilmhamane** [MicrosoftLearning/DP-203-Data-Engineer#9]
# Module: 00
#### Step: 00

Description of issue

Full setup instructions is not working. it is showing 404 error when opening
Repro steps:

1.
1.
1.

**Comment by ctesta-oneillmsft** [comment]
You need to be specific. 

I can run

1. Use the Windows Search box to search for Windows PowerShell, and then run it as an administrator.

2. In Windows PowerShell, run the following commands to download the required course files. This may take a few minutes.

mkdir c:\dp-203

cd c:\dp-203

git clone https://github.com/microsoftlearning/dp-203-data-engineer.git data-engineering-ilt-deployment

3. In Windows PowerShell, run the following command set the execution policy so you can run a local PowerShell script file:

Set-ExecutionPolicy Unrestricted

please can you log another isue with more specific details on the error.

FInally, are you running this in the virtual machine that is provided by a Lab hoster?
