### ISSUE TITLE
New Setup Scripts (part 1-3) introduce unnecessary costs for Cosmos DB

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/DP-203-Data-Engineer#91]
# Module: 00
#### Step: 00

Description of issue
Part 01 deploys a Cosmos DB with 10000 RUs and part 03 fills cosmos db and reduces the scale settings to 400 RUs. 
Part 01 is executed in Lab 0 and meanwhile Cosmos DB is provisioned with 10000 RUs until the end of Lab 05 where part 03 is executed.

Better update the json file and deploy CosmosDB with 400 RUs.

![image](https://user-images.githubusercontent.com/10166617/152830420-e85a2313-8043-40e5-af0d-07c7f013f909.png)

Repro steps:

1.
1.
1.

**Comment by TheJamesHerring** [comment]
should be resolved now. thanks for reporting.
