### ISSUE TITLE
Lab 4/Exer1/Task1/Step5 - No data in wwi-02 container

### ISSUE THREAD

**Issue by DynamicChipmunk** [MicrosoftLearning/DP-203-Data-Engineer#92]
## Lab/Demo: 04
Exercise 1
#### Step: 05

Description of issue

At step 5, the wwi-02 container has no entries thus cannot proceed with instructions:

![image](https://user-images.githubusercontent.com/80363587/153103762-e7131f8b-9d45-40df-8002-6c5243fcdd0d.png)

Repro steps:

- Fresh VM environment, from ALH hoster.
- Fresh Azure Pass, redeemed to a fresh throwaway outlook.com email account that has never had an AP redeemed to it before. (and was created for this test)
- Git clone instructs followed to get up-to-date files as-of today.
- Initial Azure region chosen by the Lab 0 setup script was westurope

1. Fellow specified Lab 4 prerequisite steps of 'setup steps to create your lab environment' -- which I assume to be successful completion of 'LAB_00_lab_setup_instructions.md' + successful completion of 'Lab 4/Task 1: Create dedicated SQL pool'.  Had no errors.

1. SQL pool present, no errors, started.

1. Complete 'Task 2: Execute PowerShell Script'

1. Receive 3 errors in that ('setup-sql.ps1') script:

![image](https://user-images.githubusercontent.com/80363587/153104301-1a16dd65-dc63-4853-8a7b-c614317b2d67.png)

![image](https://user-images.githubusercontent.com/80363587/153104441-7b1a4eb3-129e-400d-a935-54a068889e85.png)

(2 of these 3 errors are referenced in LAB_01_compute_and_storage_options.md as 'Potential errors that you can ignore', though this is not specified in Lab 4 instructions) 

Troubleshooting:
- Tried re-running the same script, but it errors indicating objects already created:

![image](https://user-images.githubusercontent.com/80363587/153104999-6acef378-c74e-4b16-aafa-81d387b347df.png)

- Tried fully deleting original 'data-engineering-synapse-xxxxxx' RG, and following Lab 0 steps again to re-run initial setup script/steps with no errors.  Region chosen this time was northeurope.  

- Re-ran Lab 4 steps again - identical 3 errors as referenced above.

- Would like to delete *all* RGs, and retry everything from complete beginning - this time running any setup scripts in Labs 1/2/3 sequentially just to see if this has any effect on success/fail of Lab 4, but several other RGs do not allow me to delete them.  Plus, ran out of troubleshooting time.

- Will save my lab and let time elapse overnight, in case this is just a matter of Azure Synapse not displaying resources promptly.

*** Is my premise wrong that Lab 4 can be run after Lab 0/setup steps?  Or has anyone else seen this, have any ideas on what might be failing to cause this?

**Comment by molenaar** [comment]
Did you run the renewed scripts?
Module 0: dp-203-setup-part01.ps1
Module 1: dp-203-setup-part02.ps1
Module 5: dp-203-setup-part03.ps1

Better run all the scripts at day 1, because part01 leaves you with CosmosDB running on 10.000 RUs.

>Would like to delete all RGs, and retry everything from complete beginning 
Just remove the dataengineering resource group. When databricks and synapse are deleted, these 'hidden' resource groups are removed automatically.

Just start with a new setup, and perhaps another one and execute all parts (part 1, 2 and 3) and check if the environment is setup correctly. I had also trouble with a few setups this week.
Throw them away and start over again.....

>At step 5, the wwi-02 container has no entries
Also look in the datalake storage account, not the workspace account. Data should (also) exist in the datalake account.

**Comment by molenaar** [comment]
Please rerun part02 again and after that sqlthe -setup.ps1 script

**Comment by TheJamesHerring** [comment]
I will leave open to see @DynamicChipmunk is able to get desired results.  These labs contain inter-dependencies on prior labs/scripts and it appears you may have skipped some instructions or prior scripts.

**Comment by DynamicChipmunk** [comment]
Thanks all - I will do a brand-new run through, and run all scripts sequential from labs 0/1/2/3 and only then 4, and see how that works.

Sounds like my premise that Lab 4 could be run 'independently', with only needing the lab 0 setup script is wrong!

**Comment by DynamicChipmunk** [comment]
Confirmed, please do close this up - After running fresh instance & Lab 0 setup script, followed by Lab 1 setup script I saw all data in synapse as expected.  Running the Lab 4 setup script then succeeded.

Apologies for wild goose chase - I shouldn't have assumed lab 4 could be 'jumped' to independently!
