### ISSUE TITLE
Lab 5, Exercise 2, Task 3 - Cannot run Part 3 script

### ISSUE THREAD

**Issue by cjpluta** [MicrosoftLearning/DP-203-Data-Engineer#93]
# Lab 5
Exercise 2
Task 3
Step 3
The Part 3 script of loading data into Cosmos DB

Description of issue
The script appears to assume that you might be using the same PowerShell session as the previous scripts, and therefore have the variables already set. However, I don't believe that this is a valid expectation for students. Even while testing, I had closed the PowerShell window between labs.

If you run only the Part 3 script, you receive a ton of errors because they are not defined within the script:
![image](https://user-images.githubusercontent.com/27508895/153123666-494bd621-9b01-412e-9539-90822ec26a68.png)

**Comment by molenaar** [comment]
![image](https://user-images.githubusercontent.com/10166617/153163117-42afbcfe-cbf4-45b4-81d4-f9ce50850ae5.png)

**Comment by molenaar** [comment]
Are you using the right azure pass? Your pass seems to be disabled.

![image](https://user-images.githubusercontent.com/10166617/153163445-09619eae-b937-4d34-9626-8a5ddb498105.png)

**Comment by TheJamesHerring** [comment]
Please use an active account.
