### ISSUE TITLE
setup-sql.ps1 returns error

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-203-Data-Engineer#95]
# Module: 4
#### Step: 3

Description of issue: setup-sql.ps1 returns an exception while creating the wwi_perf.Sale_Heap table in the dedicated pool. 

![image](https://user-images.githubusercontent.com/53346841/154254377-f24d8a42-1fc6-428d-a392-9afb10a5ce4f.png)

However, the table has been created successfully:

![image](https://user-images.githubusercontent.com/53346841/154254586-f36a6dd1-1861-4220-a680-e6ec653dd84c.png)

The problem here is that the Wait-ForSQLQuery function is waiting for the pending operation to be properly completed - by means of a label that is not present there. It should look for the label "CTAS : Sale_Heap" but cannot find it when executing the SQL "select status from sys.dm_pdw_exec_requests"

![image](https://user-images.githubusercontent.com/53346841/154255248-261ae17b-7a5e-4b06-92dd-c5769758e4da.png)

**Comment by TheJamesHerring** [comment]
please reset machine and try again.
