### ISSUE TITLE
setup_sql.ps1 cannot create user in database

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/DP-203-Data-Engineer#96]
# Module: 4
#### Step: 3

Description of issue

When executing setup_sql.ps1 you might get into an exception when the script is creating users in the database. This happens with Azure Pass Subscription (in which people are using a Microsoft account like @hotmail.com)

![image](https://user-images.githubusercontent.com/53346841/154258643-c9a61f0c-7af3-439f-9b62-ac3e7998f17b.png)

Repro steps:

1.
1.
1.

**Comment by TheJamesHerring** [comment]
@weslbo is this a common occurrence or does it happen infrequently or intermittently?

**Comment by weslbo** [comment]
I had a few participants with this issue. Didn't deliver this training anymore since then.

**Comment by TheJamesHerring** [comment]
@weslbo , I checked with my hotmail and it worked but will keep my eyes open for any more occurrences.  Thanks JH
