### ISSUE TITLE
TypeError: 'JavaPackage' object is not callable in 3.Streaming-With-Event-Hubs-Demo notebook

### ISSUE THREAD

**Issue by ngeorgeault** [MicrosoftLearning/DP-203-Data-Engineer#97]
# Module: 11
#### Step: 02

Description of issue
I got the following TypeError message at Cmd13 execution.

TypeError: 'JavaPackage' object is not callable---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<[command-4020421268244631]()> in <module>
      1 # For 2.3.15 version and above, the configuration dictionary requires that connection string be encrypted.
      2 ehWriteConf = {
----> 3   'eventhubs.connectionString' : sc._jvm.org.apache.spark.eventhubs.EventHubsUtils.encrypt(connection_string)
      4 }
      5 

TypeError: 'JavaPackage' object is not callable

Repro steps:

1. Run the 3.Streaming-With-Event-Hubs-Demo
2. Everything goes well till Cmd12
3. Run Cell Cmd13 and you'll get the error message.

**Comment by TheJamesHerring** [comment]
Is this in the lab environment?

**Comment by TheJamesHerring** [comment]
unable to repeat and never heard back from Nicolas
